---
title: "Flex Day 3"
---

# During Class
## Brain Gains
Match the expressions, equations, or functions in column 1 with descriptions in column 2.

| Probability expressions/equations/functions | Descriptions |

| --- | --- |

| **1.** $f(x) = F'(x)$ where $F(x)$ is the CDF of a continuous random variable | **A.** Cumulative Distribution Function (cdf) |

| **2.** $P(a \leq X \leq b) = \int_a^b f(x) dx = F(b) - F(a)$ | **B.** Probability Density Function (pdf) |

| **3.** $F(x) = P(X \leq x)$ | **C.** Accumulation Function |

| **4.** Given $g(x) \geq 0$, we compute $\int_{-\infty}^\infty g(x)dx$. | **D.** Total Area ("of a rug" or "under a nonnegative function") |

| **5.** $\int_{-\infty}^x f(s)ds$. | **E.** Fundamental Theorem of Calculus (FTC) |

| **6.** Given $f$ is continuous, then $\diff{}{x}(\int_{-\infty}^x f(t)dt) = f(x)$. |  |

| **7.** $\frac{\int_{-\infty}^x R(t)dt}{\int_{-\infty}^\infty R(x)dx}$ where $R$ is nonnegative |  |

| **8.** Given $h$ is continuous and $H(x) = \int_{-\infty}^x h(t)dt$, then $H'(x) = h(x)$. |  |

<details>
<summary>Answers</summary>

1. B<br>
2. E<br>
3. A<br>
4. D<br>
5. C<br>
6. E<br>
7. A<br>
8. E

</details>

## Group Meeting 
Give each group member 1-2 minutes to share what they prepared from the between class work.

Work on the chalkboard as you complete these activities and exercises, and pass the chalk as you finish each one. Leave up your work so that you can compare your answers with your neighbors. If you notice an answer differs from a neighboring group's, then have a discussion with them.
### Fundamental Theorem of Calculus Exercises
1. Compute $\int_{-2}^{1} 5 - 6x dx$ using the FTC. Check your work with Mathematica.

1. Explain why $\frac{d}{dx}\left(\int_{-2}^{1} 5 - 6x dx\right) = 0$.
1. Compute $\frac{d}{dx}\left( 5x - 3x^2 + C\right)$.

1. Compute $\frac{d}{dx}\left(\int_1^x 5 - 6t dt\right)$.
1. Compute $\int_1^x 5 - 6t dt$.

1. Compute $\frac{d}{dx}\left(\int_7^x \ln(t^2+1)e^{4t^3}dt\right)$.

1. Compute $\int e^t+\frac{1}{t}dt$.

1. Compute $\int_1^x e^t+\frac{1}{t}dt$.

## Discussion
### Change of Variables
Recall: We use the symbol, $\int f(x) dx$, to represent the collection of all antiderivatives of the function $f(x)$. Remember antiderivative means "undo" the derivative.

We also read $\int f(x) dx$ as "the indefinite integral of $f$".

Evaluate each indefinite integral.
- $\int (5x^2 + 1)^3 10x dx$

- $\int \frac{t}{\sqrt{t^2 - 1}} dt$

- $\int \frac{t + 2t^2}{\sqrt{t}} dt$

- $\int (5-x)^2 dx$

- $\int -2x\sqrt{9-x^2} dx$

- $\int x^2(x - \frac{2}{x}) dx$

- $\int (3x+1)^2dx$

- $\int y(4y^2 + 3)^5 dy$

- $\int \left(\frac{y^4 - 7}{y^2}\right) dy$

- $\int \frac{1}{4w - 1} dw$

- $\int \frac{1}{x^2 + 8} dx$

<details>
<summary>Check</summary>

- We see $\int (5x^2 + 1)^3 10x dx = \frac{1}{4}(5x^2 + 1)^4 + C$.

- We see $\int \frac{t}{\sqrt{t^2 - 1}} dt = \sqrt{t^2 - 1} + C$.

- We see $\int \frac{t + 2t^2}{\sqrt{t}} dt = \frac{2}{5}t^{5/2} + \frac{2}{7}t^{7/2} + C$.

- We see $\int (5-x)^2 dx = -\frac{1}{3}(5-x)^3 + C$.

- We see $\int -2x\sqrt{9-x^2} dx = \frac{2}{3}(9-x^2)^{3/2} + C$.

- We see $\int x^2(x - \frac{2}{x}) dx = \frac{1}{4}x^4 - \frac{2}{3}x^3 + C$.

- We see $\int (3x+1)^2dx = \frac{1}{9} (3x+1)^3 + C$.

- We see $\int y(4y^2 + 3)^5 dy = \frac{1}{48}(4y^2+3)^6 + C$.

- We see $\int \left(\frac{y^4 - 7}{y^2}\right) dy = \frac{1}{3}y^3 + \frac{7}{y} = C$.

- We see $\int \frac{1}{4w - 1} dw = \frac{1}{4}\ln(|4w-1|) + C$.

- We have not yet learned a technique that we can use to find this integral, $\int \frac{1}{x^2 + 8} dx$, by hand.

</details>

<a id="Prep"></a>
# Between Class Sessions <a id="tasklist"></a>
## Activity - Integration Practice
Evaluate each indefinite integral (the complete "list" of antiderivatives or the most general antiderivative). When you are writing your answers **don't for get your "+C"**. Then check your answer with Mathematica. 
1. $\int (3x^2 + 1)^3 6x dx$

1. $\int x^2\sqrt{x^3 + 1} dx$
1. $\int (5-2x)^2 dx$

1. $\int x(x+2)^3 dx$
1. $\int \frac{y}{(y-3)^2} dy$

1. $\int \frac{5}{x^2 + 25} dx$ 
1. $\int \frac{5x}{x^2 + 25} dx$ 

We can use the following command in Mathematica to calculate an indefinite integral.

```
Integrate[(enter the integrand here), (enter the variable of integration here)]
```

Use Mathematica to check your answer to the exercises above for example:
- $\int (7-x)^2 dx$

```
Integrate[(7-x)^2, x]
```

Compare the answer you got in Mathematica to your answer from above.

# End of Semester Announcements
- Last day of classes is April 5
    - Last day to work on Knewton Alta Homework is April 5.
    - Last day to submit Project work is April 5.
- No Final Exam

<a id="PP"></a>

## Skill Practice (KA Homework)

## Applied Practice (Project Work)
