---
title: "Schedule"
---

| Date | Notes |
|------|-------|
| Thu Oct 1 | !Group Collaborative Spaces Section 01\\ [[Group 1 Collaboration Space -> https://docs.google.com/document/d/1qphjKMfvf8ZYyWgxmPa8aR2uxxuY0OsACZgBQU16K-M/edit?usp=sharing]]\\ [[Group 2 Collaboration S |
| Fri Oct 2 | !Group Collaborative Spaces Section 01\\ [[Group 1 Collaboration Space -> https://docs.google.com/document/d/1qphjKMfvf8ZYyWgxmPa8aR2uxxuY0OsACZgBQU16K-M/edit?usp=sharing]]\\ [[Group 2 Collaboration S |
| Sat Oct 3 | THIS IS A TEMPLATE    !Agenda !!Outcomes *Outcome 1 *Outcome 2 **Smaller Outcome related to Outcome 2  !!Item 1  !!Item 2   !!PREP for [Day here]    !Group Collaborative Spaces Secti |
| Mon Oct 5 | !Group Collaborative Spaces Section 01\\ [[Group 1 Collaboration Space -> https://docs.google.com/document/d/1qphjKMfvf8ZYyWgxmPa8aR2uxxuY0OsACZgBQU16K-M/edit?usp=sharing]]\\ [[Group 2 Collaboration S |
| Tue Oct 6 | !Agenda  !!Outcomes * level 1 ** level 2    !!Explore Common Functions from Probability $f_1(x) =  \begin{cases} \frac{n!}{x!(n-x)!}p^x(1-p)^{ (n-x)} & \quad x = 0, 1, 2, 3, ... |
| Thu Oct 8 | !Agenda (10/8)  !!Outcomes *Outcome 1 *Outcome 2 **Smaller Outcome related to Outcome 2   !!Visual Fits (models of relationship) To prepare for today you created the following s |
| Fri Oct 9 | !Agenda (10/9)  !!Outcomes *Outcome 1 *Outcome 2 **Smaller Outcome related to Outcome 2    !!Intermediate Value Theorem (IVT) !!!Examples from our preparation. !!!Additional exa |
| Mon Oct 12 | !Agenda (10/12)  !!Equations of Lines !!!Formulas to Remember '''Point-Slope Form of a Line''' \\ Given a point on a line, $(x_1, y_1)$, and the slope of the line, $m$, we can write the equation of th |
| Tue Oct 13 | !Agenda (10/13)  !!Approximating a Derivative at a Point.  CODE\\ setwd("/Users/katjohnson/Documents/git/M119/class_code_sessions") \\ source("201013_class.r") \\   Exercise 1: Given $f_1(x) = x^4 - 1 |
| Thu Oct 15 | !Agenda (10/15)  !!Derivative Rules continued !!!Self Check *What are the function families we have discussed this semester?  >>toggle<< Possible Solution >>indent<< *power functions *exponent |
| Fri Oct 16 | !Agenda (10/16)  !!Derivative Rules continued !!!What derivative rules do we need? *What are the function families we have discussed this semester?  >>toggle<< Possible Solution >>indent<< *po |
| Mon Oct 19 | !!Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/imag |
| Tue Oct 20 | !!Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/imag |
| Thu Oct 22 | !!Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/imag |
| Fri Oct 23 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Mon Oct 26 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Tue Oct 27 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Thu Oct 29 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Fri Oct 30 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Mon Nov 2 | ---- !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/ |
| Tue Nov 3 | ---- !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/ |
| Thu Nov 5 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Fri Nov 6 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Sat Nov 7 | THIS IS A TEMPLATE !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=2 |
| Mon Nov 9 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Tue Nov 10 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Thu Nov 12 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Fri Nov 13 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Mon Nov 16 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Tue Nov 17 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Thu Nov 19 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Fri Nov 20 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Mon Nov 23 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Tue Nov 24 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Mon Nov 30 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Tue Dec 1 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Thu Dec 3 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Fri Dec 4 | !Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/image |
| Sat Dec 5 | Given the pdf, $f(t) = \frac{1}{\sqrt{2\pi}}e^{-\frac{(t-25)^2}{2}}$ for any real number $t$, find the following percentiles. * 50th percentile * 90th percentile * 10th percentile (: |
| Mon Dec 7 | ! Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/imag |
| Tue Dec 8 | ! Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/imag |
| Thu Dec 10 | ! Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/imag |
| Fri Dec 11 | ! Learning Reminders  %height=200px% https://static1.squarespace.com/static/577b524bff7c50a2a386f811/t/59816ef6ebbd1abb1c30b033/1501654792565/IMG_0220.JPG %height=200px% https://ih1.redbubble.net/imag |
| Mon Dec 14 | !Self Check * How do we find the system of equations to solve for the parameter values when using the maximum likelihood to fit a model? * How do we find the system of equations to solve for the param |
| Sat Dec 19 | Course Reflection (and Summary) Quiz Results: * Key Ideas ** Integrals ** Functions ** using R to plot functions ** improved basic algebra skills ** difference between PDF and CDF ** |
| Sat Jan 2 | THIS IS A TEMPLATE  [@ https://drive.google.com/uc?export=download&id= @]  ! Brain Gains  >>toggle<< Answer >>indent<<  >><<   [@ @](:co |
| Thu Jan 7 | ! Agenda 1/7 !! Devotional You must be using you byui google account to access the [[Devotional Sign-up -> https://docs.google.com/spreadsheets/d/1Y0b8pr-zTfoS9ilfTUPJ7ypzD7rHcKQzu6US-YN4nG4/edit?usp= |
| Fri Jan 8 | !Agenda 1/8 !!! Devotional    !! Check-in (in Breakout Rooms) * Did you get R and RStudio installed? * If not, where are you running into trouble?    !! Activity (Evaluating Functions) Complete the fo |
| Mon Jan 11 | !Agenda (1/11) !! Brain Gains * Give an example of a polynomial that is NOT a power function. * Give an example of a power function that is NOT a polynomial. * Given $f(x) = \sqrt{3-x}$, compute $f(-4 |
| Tue Jan 12 | ! Check-in (Breakout Rooms) Discuss your observations from your work with the Interactive Programming exercise and refections. * What does the seq() command do? * How does the plot() command work? * W |
| Thu Jan 14 | ! Brain Gains * Consider the function $T(x) = \frac{1}{2}(3(x+2))^2 - 10$.  ** Let $g(x) = c f(a(x+b)) + d$ with $a$, $b$, $c$, and $d$ constants. If $T(x) = g(x)$, answer the following questions. *** |
| Fri Jan 15 | ! Brain Gains * Given $h(x) = |x|+1$. ** Evaluate $h(x+3)+2$. *** Identify the transformation. What does this tell you about the relationship between the graphs of $h(x)$ and $h(x+3)+2$?  ** What can |
| Tue Jan 19 | ! Brain Gains * Solve the following equations. Find the exact answer. ** $3x^2 = 15$ ** $x^3 = 5x^2 - 4x$ * Write in expanded form then calculate the following values. ** $\sum_{k=4}^{8} (5-k)$ ** $\p |
| Thu Jan 21 | ! Constructing and Deconstructing Functions What are the building blocks? -- Operations and Functions * Throughout the semester we will rely on '''5 function operations'''. * Throughout the semester w |
| Fri Jan 22 | ! Exponential Functions  >>toggle<< Definition: Exponential Function (OpenStax Textbook) >>indent<< An '''exponential function''' is of the form $b^x$ where $b>0$ and $b \neq 1$.  Note: An exp |
| Mon Jan 25 | ! Solving Equations and uniroot() * [[Exponential Equations -> https://drive.google.com/file/d/1EtrZ_IgMDehf6yiBsOEHpjtQJ0roPbRv/view?usp=sharing]] * [[Log Equations -> https://drive.google.com/file/d |
| Tue Jan 26 | ! Brain Gains * Given $h(x)$, find $f(x)$ and $g(x)$ so that $f(g(x)) = h(x)$. ** $e^{4x-1} + 7$ ** $4\sqrt[3]{x+0.2}$ ** $\ln(\frac{3x}{5x+1})$  * Write in expanded form. ** $\sum_{i=5}^{10} 3i^2$ ** |
| Thu Jan 28 | ! Function are Models -- Models are Stories -- Tell the Story * The local elvish population is modeled by the function $P(x;a,b) = ax+b$, where $x$ is the number of years since 2000. ## Pick parameter |
| Fri Jan 29 | ! Probability  >>toggle<< Definition: Probability >>indent<< * An '''experiment''' is a process that produces an observation. * An '''outcome''' is a possible observation. * The set of all pos |
| Mon Feb 1 | ! Probability  >>toggle<< Conditional Probability >>indent<< The '''conditional probability''' of $A$ given $B$ is written $P(A | B)$. Conditional probability is used to compute the probabilit |
| Tue Feb 2 | ! Brain Gains * Write down a formula for the residual, $y - \hat{y}$, given the model $f(x) = b + mx$. * Write down a formula for the residual, $y - \hat{y}$, given the model $g(x) = c + bx + a\ln(4x) |
| Thu Feb 4 | ! Learning is Not Easy Learning requires Time, Effort, and Engagement.      ! Project Work !!! Project 1 * Chose a break out room and make some progress on your Project 1. ** Ask questions. ** Articul |
| Fri Feb 5 | ! Introduction to Linearization * Plot each of the following functions and then zoom in at the specified location. ** $f_1(x) = x^4 - 10x^2 + 3x$ at $x=3$ ** $f_2(x) = e^{2x} - 1$ at $x=0$ ** $f_3(x) |
| Sat Feb 6 | THIS IS A TEMPLATE    *Consider the function $h(y;a,b) = \frac{a^2y - 4ab + y^2}{a - 3by}$. Take the derivative with respect to $y$, assume all other variables and parameters are con |
| Mon Feb 8 | ! Brain Gains * Residuals (or errors) revisited. Given a list of $n$ measurements, $(x_i, y_i)$, and a model, $f$, you can write the formula for the errors (or residuals), $y_i - \hat{y_i} = y_i - f(x |
| Tue Feb 9 | ! Project Work !!! Project Check-in (or Project 2 Task 1) * Chose a break out room and make some progress on your Projects. ** Ask questions. ** Articulate what you do understand. ** Articulate challe |
| Thu Feb 11 | ! What derivative rules do we need? *What are the function families we have discussed this semester?  >>toggle<< Possible Solution >>indent<< *power functions *exponential functions *logarithm |
| Fri Feb 12 | !!! Loglikelihood Write the loglikelihood function for the errors in each situation below, assume the errors are independent and normally distributed (with mean of 0 and standard deviation of 1).   '' |
| Mon Feb 15 | !!! Derivative Rules and Sum Notation Exercises Find the indicated derivative. * Given $f(a_1; x) = \sum_{i=1}^{3} (a_1x_i + 2)^5$, find $\diff{f}{a_1}$. * Given $g(a_1, a_2; x) = \s |
| Tue Feb 16 | !!! Project Work * Chose a break out room. ** Ask questions. ** Articulate what you do understand. ** Articulate challenges you are facing and things are you having trouble understanding. ** Ask for f |
| Thu Feb 18 | !!! Derivative Practice * Consider the function $g(x) = \sqrt{\frac{x+7}{2x^5-3x+4}}$. ** Find the derivative of $g$ with respect of $x$. ** Find the linear approximation of $g$ at $x=0$.      !!! Par |
| Fri Feb 19 | !!! Check-in * Questions from between class work or Knewton Alta assignments.  ->[[Additional Practice (Partial Derivatives) -> https://docs.google.com/presentation/d/1qfi0ZCXSE9pL3e_rNomB58P9TPErytWV |
| Mon Feb 22 | !!! %newwin%[[Derivative Relationships Activity -> https://docs.google.com/presentation/d/1_cnGOLfJDfDUXfGzyfGyKVaxSsX506cPax2bKbKEsG0/edit?usp=sharing]]      !!! Partial Derivatives and loglikelihood |
| Tue Feb 23 | !!! Project Work * Chose a break out room. ** Ask questions. ** Articulate what you do understand. ** Articulate challenges you are facing and things are you having trouble understanding. ** Ask for f |
| Thu Feb 25 | !!! %newwin%[[Derivative Relationship Practice -> https://docs.google.com/presentation/d/1DqaglYekQXaXzSBUjKmWpdW02v4IHr6Lr945vk5YohI/edit?usp=sharing]]      !!! Practice with Optimization * A farmer |
| Fri Feb 26 | !!! %newwin%[[Derivative Relationship Practice -> https://docs.google.com/presentation/d/1DqaglYekQXaXzSBUjKmWpdW02v4IHr6Lr945vk5YohI/edit?usp=sharing]]  >>toggle<< Solution (slide 4) >>indent |
| Mon Mar 1 | !!! Identifying Maximums and Minimums in Higher Dimensions '''Q: What would the first derivative test look like in 2 dimensions?'''   >>toggle<< Definition: Critical Points (2 dimensions) >>in |
| Tue Mar 2 | * Devotional sign-up  !!! Course Grade Check-in  We are about 2/3 the way through the semester, approximately 4 weeks left. * How are you doing? ** Knewton Alta (skills practice) *** How many function |
| Thu Mar 4 | !!! Step of Optimization * Identify the Function of Interest (the objective function) ** This is the function you want to make big (maximize) or small (minimize). * Optimize ** Take the first and seco |
| Fri Mar 5 | !!! More Practice with Maximum Likelihood Method (2D) Goal: Fit deterministic models to data using the maximum likelihood method (an optimization method).   * Example: Consider the model $h(x) = mx + |
| Sat Mar 6 | THIS IS A TEMPLATE   [@ https://drive.google.com/uc?export=download&id= @]   >>toggle<<  >>indent<<  >><<   [@ @]  ! Between |
| Mon Mar 8 | !!! Reading Check-in * Calculating Average Values Consider the vector of integers c(2,2,2,3,3,5,5,5,5,7,8,8,9). ** Find the mean of the values by summing the values and then dividing by the number of |
| Tue Mar 9 | !!! Project Work * Chose a break out room. ** Ask questions. ** Articulate what you do understand. ** Articulate challenges you are facing and things are you having trouble understanding. ** Ask for f |
| Thu Mar 11 | !!! Rugs for Continuous Random Variables Let's suppose for a minute that we have a rug (as shown in each figure created using the draw_rug function) and a trap door on the ceiling above the rug.  Each |
| Fri Mar 12 | !!! Key Ideas (Rugs & Continuous Random Variables)  >>toggle<< The cumulative distribution function (CDF) of a random variable >>indent<< The '''cumulative distribution function''' of a random |
| Sat Mar 13 | !!! Rugs for Continuous Random Variables Let's suppose for a minute that we have a rug (as shown in each figure) and a trap door on the ceiling above the rug.  Each time we open the |
| Mon Mar 15 | !!! Probability '''Density''' Consider the random variable $X$ with the PDF $f$.\\ $f(x) =  \begin{cases} \frac{1}{6} & \quad 1 \leq x \leq 7\\ \\ 0 & \quad \text{otherwise}. \end{cases}$  * Compute $ |
| Tue Mar 16 | !!! Project Work * Chose a break out room. ** Ask questions. ** Articulate what you do understand. ** Articulate challenges you are facing and things are you having trouble understanding. ** Ask for f |
| Thu Mar 18 | !!! Questions: Expected Value and Variance Exercises %newwin%[[Slides -> https://docs.google.com/presentation/d/1Dz9sfkqfGU5saiMdboy0bLZeyXyOqkjz9E6aroM_7V0/edit?usp=sharing]]      !!! Normal and Gamm |
| Fri Mar 19 | !!! Practice: Definite Integrals and Geometric arguments Use a geometric (area) argument to find the value of each integral. Check your solution with software. * $\displaystyle\int_0^4 \sqrt{16-x^2} d |
| Mon Mar 22 | !!! Properties of the Definite Integral %newwin%[[Slides -> https://docs.google.com/presentation/d/1kiiu7vBa4h3Pz4detLBgtRKOZeSsM7FPENtqGylbb0M/edit?usp=sharing]]   >>toggle<< Definite Integra |
| Tue Mar 23 | !!! Solving Systems %newwin% [[Slides -> https://docs.google.com/presentation/d/1mz80cZPqjUCAjaC1CpNmv3CzDijuv-f95Vrc92Rg1wE/edit?usp=sharing]]      !!! Method of Moments continued Big Idea: The '''me |
| Thu Mar 25 | !!! Calculate a Percentile  >><< >>toggle<< Definition: Percentile  >>indent<< * A percentile is a number, $x_p$, that satisfies the equation $P(X \leq x_p) = \frac{p}{100}$. ** In other words |
| Fri Mar 26 | !!! Accumulation Function Let $g(x)$ be a function that defines the top of a rug and each rug have a matching trap door above it. Each time we open the trap door, a dart falls from the door onto the r |
| Mon Mar 29 | >>toggle<< Summary: Calculating Probability with the PDF and CDF >>indent<< * Calculating Probability with the PDF. ** $P(X \leq a) = \int_{-\infty}^a f(x)dx$ ** $P(a \leq X \leq b) = \int_a^ |
| Tue Mar 30 | !!! Brain Gains Match the expressions, equations, or functions in column 1 with descriptions in column 2. ||border=1 width=80% ||!Probability expressions/equations/functions   ||!Descriptions |
| Thu Apr 1 | ! Reminders: * Monday, April 5 '''(at 8am)''': Last Day first submission of a Project Task or Project will be accepted (for Projects you have already been work on throughout the semester).  * Tuesday, |
| Fri Apr 2 | !!! Comparing Solutions How do our answers to the following indefinite integrals compare when compute by hand or use Mathematica?  * Consider $\int (7-x)^2 dx$. ** Computing by had we find $\int (7-x) |
| Mon Apr 5 | !!! Applying Mathematics to Data Analytics -- Course Reflection !!!! Topics & Tools * Function * Function Transformations * Parameters * General Forms * Evaluate a Function * Solve and Equation * Deri |
| Tue Apr 6 | !!! Project & Knewton Alta Work * Chose a break out room. ** Ask questions. ** Articulate what you do understand. ** Articulate challenges you are facing and things are you having trouble understandin |
| Mon Apr 19 | !Today's Agenda !!Mastery Learning - Specifications Grading #What is %newwin%[[mastery learning->https://youtu.be/-MTRxRO5SRA?t=137]]? #What is %newwin%[[specifications grading->https://www.insidehigh |
| Tue Apr 20 | Jamboards   !Agenda  !! Check-in (in Breakout Rooms - 5 mins) * Did you get R and RStudio installed? * If not, where are you running into trouble?    !! Activity (Evaluating |
| Thu Apr 22 | ! In class !!Classifying Functions -- Activity (Follow-up) Jamboards  Last time we ended class working on this exercise.   *Open your corresponding Jamboard.  *Classify each |
| Fri Apr 23 | ! In class !!Knewton Alta Followup In this %newwin%[[Google Doc -> https://docs.google.com/document/d/1BQyA7LqMaSrTIml_FrOHLXLSqoOsB0Xv9m7jHgPrd2s/edit?usp=sharing]], you shared a picture of one probl |
| Mon Apr 26 | !In class !! Brain Gains Jamboards  ---- * Consider the function $T(x) = \frac{1}{2}(3(x+2))^2 - 10$.  ** Let $g(x) = c f(a(x+b)) + d$ with $a$, $b$, $c$, and $d$ constants. |
| Tue Apr 27 | !Follow Up *Prep Questions?  **%newwin%[[2021-04-26 Function Notation->https://docs.google.com/document/d/1J9IzFZSk8TjsUUBbgOr6ckXHC5-tQYTSQ-nVdM8t3BQ/edit]] ! Brain Gains Jamboards (:include Main.Jam |
| Thu Apr 29 | !Follow Up *Any questions from from the preparation (see [[Between Class Sessions Tasklist->Schedule.20210427#tasklist]])? **Describing Function (practice Reading Mathematics) **Practice with Function |
| Fri Apr 30 | !Follow Up *Any questions from from the preparation (see [[Between Class Sessions Tasklist->Schedule.20210429#tasklist]])? **Desmos Activity **Practice with Functions %newwin%[[GoogleDrive->https://do |
| Mon May 3 | ! Exponential Functions  >>toggle<< Definition: Exponential Function (OpenStax Textbook) >>indent<< An '''exponential function''' is of the form $b^x$ where $b>0$ and $b \neq 1$.  Note: An exp |
| Tue May 4 | ! Brain Gains * Rewrite $\log \left(\prod_{n=2}^5(7 - ny)\right)$ using log properties.  * For each function, $h(x)$, below find functions $f(x)$ and $g(x)$ so that $f(g(x)) = h(x)$. ** $h(x) = e^{4x- |
| Thu May 6 | ! Brain Gains * Write in expanded form. ** $\sum_{i=5}^{10} 3i^2$ ** $\prod_{k=1}^{4}(1-k^2)$ * Use log properties to write $\ln\left(\prod_{k=1}^{4}(1-k^2)\right)$ as a sum of logarithms.       ! Sol |
| Fri May 7 | ! Brain Gains * Rewrite the following expression using the properties of logarithms. ** $\log \left( \prod_{j=1}^{3} (x + j) \right)$ ** $\log_4 \left( \prod_{k=1}^{5} (y_k + b x_k)^2 \right)$ ** $\ln |
| Mon May 10 | !Follow Up *Last Time's %newwin%[[Between Class Sessions->http://byuimath.com/bmw/all/119/index.php?n=Schedule.20210507#tasklist]] **%newwin%[[Prep Upload->https://docs.google.com/document/d/1A4wVMcLV |
| Tue May 11 | !Follow Up *Last Time's %newwin%[[Between Class Sessions->http://byuimath.com/bmw/all/119/index.php?n=Schedule.20210510#tasklist]] **%newwin%[[Prep Upload->https://docs.google.com/document/d/1A4wVMcLV |
| Thu May 13 | !Follow Up *Last Time's %newwin%[[Between Class Sessions->http://byuimath.com/bmw/all/119/index.php?n=Schedule.20210511#tasklist]] **%newwin%[[Prep Upload->https://docs.google.com/document/d/1A4wVMcLV |
| Fri May 14 | !Follow Up *Last Time's %newwin%[[Between Class Sessions->http://byuimath.com/bmw/all/119/index.php?n=Schedule.20210513#tasklist]] **%newwin%[[Prep Upload->https://docs.google.com/document/d/1A4wVMcLV |
| Mon May 17 | ! Follow Up * Last Time's %newwin%[[Between Class Sessions->http://byuimath.com/bmw/all/119/index.php?n=Schedule.20210514#tasklist]] ** %newwin%[[Prep Upload->https://docs.google.com/document/d/1A4wVM |
| Tue May 18 | ! Project Work We'll start by having someone share what they did last week with Task 3. Then we'll split into break out rooms for 20 minutes to work on %newwin%[[Task 4->https://byuistats.github.io/M1 |
| Thu May 20 | ! Follow Up * Last Time's %newwin%[[Between Class Sessions->http://byuimath.com/bmw/all/119/index.php?n=Schedule.20210518#tasklist]] ** %newwin%[[Prep Upload->https://docs.google.com/document/d/1A4wVM |
| Fri May 21 | ! Follow Up * Last Time's %newwin%[[Between Class Sessions->http://byuimath.com/bmw/all/119/index.php?n=Schedule.20210520#tasklist]] ** %newwin%[[Prep Upload->https://docs.google.com/document/d/1A4wVM |
| Mon May 24 | Instructor note on this page.   I don't like the order of the problems below.  It was a "game" before. I think the order needs to increase differently, to help the studen |
| Tue May 25 | ! Project Work * Project 1 is due this week. Project 2 Task 1 is due next week (we don't have class Monday or Tuesday).  * Share your work.  I'd love to have two volunteers share what they did for Pro |
| Thu May 27 | ! Check-in * Last Time's  **      ! Brain Gains * Find the derivative of each of the following: ** $f_1(x) = (3x^2+4)^5$ ** $ |
| Fri May 28 | ! Check-in * Last Time's  ** %newwin%       ! %newwin%[[Derivative Relationships Activity -> https://docs.google.com/presenta |
| Thu Jun 3 | ! Check-in * Last Time's  **   ** We'll use the %newwin%[[Class Jamboard->https://jamboard.google.com/d/1OoPTyRZ6FR2d3dT5yf-F |
| Fri Jun 4 | ! Check-in * Last Time's  **              ! Maxima and Minima (Extrema) Examples Today we'll be using R to help us locate ext |
| Mon Jun 7 | ! Check-in * Week 7 Progress report - Autograding messed up. Just report what you did for Thursday/Friday last week.  I'll manually update the scoring.  * Last Time's (:include Link.BetweenClassSessio |
| Tue Jun 8 | ! Check-in * Last Time's  **    ! Project Work Goal: Fit deterministic models to data using the maximum likelihood method (an |
| Thu Jun 10 | ! Check-in * Last Time's  **   ** Let's solve the system of equations that results from $\frac{d\ell_2}{da_1} = 0$ and $\frac |
| Fri Jun 11 | ! Check-in * Last Time's  **       ! Optimizing loglikelihood to Fit a (deterministic or relationship) Model to Data We have |
| Mon Jun 14 | ! Check-in * Last Time's  **       ! Reminders  >>toggle<< Steps of Optimization >>indent<< * Identify the Function o |
| Tue Jun 15 | ! Check-in * Last Time's  **       ! Project Work As you work in pairs or groups as assigned, write down your work on the Jam |
| Thu Jun 17 | ! Check-in * Last Time's  **       ! Least Squares Regression: Another method for fitting a model to data Have you heard the |
| Fri Jun 18 | ! Check-in * Last Time's  **   ! Compare loglikelihood and least squares Read in this data with the following code. [ |
| Mon Jun 21 | ! Check-in * Last Time's  **   !!Exercises 1.1 - Averaging Test Scores *%newwin%[[Exercises 1.1->https://byuistats.github.io/ |
| Tue Jun 22 | ! Check-in * Last Time's  **    ! Key Ideas (Means, Expected Value, and Discrete Random Variables)  >>toggle<< The pr |
| Thu Jun 24 | ! Check-in '''Rugs for Continuous Random Variables'''\\ Let's suppose for a minute that we have a rug (as shown in each figure created using the draw_rug function) and a trap door on the ceiling above |
| Fri Jun 25 | ! Key Ideas (Rugs & Continuous Random Variables)  >>toggle<< The cumulative distribution function (CDF) of a random variable >>indent<< The '''cumulative distribution function''' of a random v |
| Mon Jun 28 | ! Check-in * Last Time's  ** %newwin%  ! Probability '''Density''' Consider the random variable $X$ with the PDF $f$.\\ $f(x) |
| Tue Jun 29 | ! Check-in * Last Time's  **       ! Riemann Sums and the Definite Integral !! Example 2 Consider the rug with top defined by |
| Thu Jul 1 | ! Check-in * Last Time's  **       ! Normal and Gamma Random Variables * Let $Y$ be a Normal random variable with the probabi |
| Fri Jul 2 | ! Check-in * Last Time's  **       ! Practice: Definite Integrals and Geometric arguments Use a geometric (area) argument to |
| Mon Jul 5 | ! Check-in * Last Time's  **    !! Properties of the Definite Integral  >>toggle<< Definite Integral >>indent<< For a |
| Tue Jul 6 | ! Check-in * Last Time's  **    !! Properties of the Definite Integral  >>toggle<< Definite Integral >>indent<< For a |
| Thu Jul 8 | ! Some Probability Functions and Calculations Reminders  >>toggle<< The cumulative distribution function (CDF) of a random variable >>indent<< The '''cumulative distribution function''' of a r |
| Fri Jul 9 | ! Check-in * Last Time's  **    ! Accumulation Function Let $g(x)$ be a function that defines the top of a rug and each rug h |
| Mon Jul 12 | ! Check-in * Last Time's  **       ! Antiderivatives If $F(x)$ is an antiderivative of $f(x)$, then $G(x) = F(x) + 11$ is als |
| Tue Jul 13 | ! Check-in * Last Time's  **      ! Brain Gains Match the expressions, equations, or functions in column 1 with descriptions |
| Thu Jul 15 | ! Check-in !! Brain Gains * $\int (2x+7)^4dx$ * $\int \frac{1}{3t - 1} dt$ * $\int e^{-5s} ds$ * $\int (x^2-6x+9)^3dx$  * Last Time's  ** (:include L |
| Fri Jul 16 | ! Check-in * Last Time's  ** %newwin%      ! Comparing Solutions How do our answers to the following indefinite integrals com |
| Mon Jul 19 | ! Check-in * Last Time's  ** %newwin%      ! Applying Mathematics to Data Analytics -- Course Reflection !! Topics & Tools * |
| Wed Sep 8 | !Does this work !Even with headings !!and how are subs made !!!What does this look like. !It isn't enabled |
| Mon Sep 13 | !During Class  %height=50px%https://blogcdn.4tests.com/wp-content/uploads/2015/09/Screen-Shot-2015-09-11-at-5.40.48-PM.png !!Brain Gains  1. Let $f(x,y) = 4x^2 -5y\sqrt{x+1}$. Find each of the followi |
| Tue Sep 14 | *Pizza Lunch on Thursday: %newwin%[[Vaccination Clinic->https://www.byui.edu/covid-19-updates#vo]]  !During Class   * For the function $$\ds f(x) |
| Wed Sep 15 | Before class begins, remember to complete the following. #Complete the %newwin%[[Preparation Tasks->Schedule.20210914#tasklist]]  #%newwin%[[Upload->https://docs.google.com/document/d/1Ec0rZbAG-DrTB-m |
| Thu Sep 16 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Sep 17 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Sep 20 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Sep 21 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Sep 21 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Sep 23 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Sep 24 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Sep 27 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Sep 28 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Sep 30 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Oct 1 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Oct 4 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Oct 5 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Oct 7 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Oct 8 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Oct 11 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Oct 12 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Oct 14 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Oct 15 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Oct 18 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Oct 19 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Oct 21 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Oct 22 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Oct 25 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Oct 26 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Oct 28 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Oct 29 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Nov 1 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Nov 2 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Nov 4 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Nov 5 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Nov 8 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Nov 9 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Nov 11 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Nov 12 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Nov 15 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Nov 16 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Nov 18 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Nov 19 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Nov 22 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Nov 23 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Nov 29 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Nov 30 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Wed Dec 1 | Before class begins, remember to complete the following. #Complete the %newwin%[[Preparation Tasks->Schedule.20211130#tasklist]] (loaded below).  #%newwin%[[Upload->https:/ |
| Thu Dec 2 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Dec 3 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Dec 6 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Tue Dec 7 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Thu Dec 9 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Fri Dec 10 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Dec 13 | [[Head to this page->Class.{*$Name}]] to see what we'll be doing in class today (it will auto load here a few minutes before class starts).   Before class begins, remember |
| Mon Apr 4 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Class.202 |
| Tue Apr 5 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Class.202 |
| Mon Apr 18 | The material for today will auto load here a few minutes before class starts. |
| Tue Apr 19 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Plans.Da |
| Thu Apr 21 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Apr 22 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Apr 25 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue Apr 26 | The material for today will auto load here a few minutes before class starts.       [[#Prep]] ! Between |
| Thu Apr 28 | The material for today will auto load here a few minutes before class starts.       [[#Prep]] ! Between |
| Fri Apr 29 | The material for today will auto load here a few minutes before class starts.       [[#Prep]] ! Between |
| Mon May 2 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue May 3 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu May 5 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri May 6 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon May 9 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue May 10 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu May 12 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri May 13 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon May 16 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue May 17 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu May 19 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri May 20 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon May 23 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue May 24 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu May 26 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri May 27 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue May 31 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu Jun 2 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Jun 3 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Jun 6 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue Jun 7 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu Jun 9 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Jun 10 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Jun 13 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue Jun 14 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu Jun 16 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Jun 17 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue Jun 21 | Happy Monday/Tuesday! The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below |
| Thu Jun 23 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Jun 24 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Jun 27 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue Jun 28 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu Jun 30 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Jul 1 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue Jul 5 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu Jul 7 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Jul 8 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Jul 11 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Tue Jul 12 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Thu Jul 14 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Jul 15 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Jul 18 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Sep 12 | The material for today will auto load here a few minutes before class starts. |
| Tue Sep 13 | *[[Plans.Day1#Prep]] *[[Plans.Day2]]    The material for today will auto load here a few minutes before class starts.   To prepare for class refer to |
| Thu Sep 15 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Fri Sep 16 | The material for today will auto load here a few minutes before class starts.   To prepare for class refer to the suggested preparation (loaded below).  (:include Schedule |
| Mon Sep 19 | *[[Plans.Day4#Prep]] *[[Plans.Day5]]    The material for today will auto load here a few minutes before class starts.   To prepare for class refer to |
| Tue Sep 20 | '+Today is Day {$:today}+' |
| Thu Sep 22 | '+Today is Day {$:today}+' |
| Fri Sep 23 | '+Today is Day {$:today}+' |
| Mon Sep 26 | '+Today is Day {$:today}+' |
| Tue Sep 27 | '+Today is Day {$:today}+' |
| Thu Sep 29 | '+Today is Day {$:today}+' |
| Fri Sep 30 | '+Today is Day {$:today}+' |
| Mon Oct 3 | '+Today is Day {$:today}+' |
| Tue Oct 4 | '+Today is Day {$:today}+' |
| Thu Oct 6 | '+Today is Day {$:today}+' |
| Fri Oct 7 | '+Today is Day {$:today}+' |
| Mon Oct 10 | '+Today is Day {$:today}+' |
| Tue Oct 11 | '+Today is Day {$:today}+' |
| Thu Oct 13 | '+Today is Day {$:today}+' |
| Fri Oct 14 | '+Today is Day {$:today}+' |
| Mon Oct 17 | '+Today is Day {$:today}+' |
| Tue Oct 18 | '+Today is Day {$:today}+' |
| Thu Oct 20 | '+Today is Day {$:today}+' |
| Fri Oct 21 | '+Today is Day {$:today}+' |
| Mon Oct 24 | '+Today is Day {$:today}+' |
| Tue Oct 25 | '+Today is Day {$:today}+' |
| Thu Oct 27 | '+Today is Day {$:today}+' |
| Fri Oct 28 | '+Today is Day {$:today}+' |
| Tue Nov 1 | Today we'll be using the day as a project work day.  Finish up project 1, work towards completing all of project 2.  We have discussed all the details in class, so now we just need to take the time to |
| Mon Nov 21 | Today we'll be using the day as a project work day.  Finish up any remaining tasks or projects. |
| Tue Nov 22 | Today we'll be using the day as a project work day.  Finish up any remaining tasks or projects. |
| Thu Jan 5 | '+Today is Day {$:today}+' |
| Fri Jan 6 | '+Today is Day {$:today}+' |
| Mon Jan 9 | '+Today is Day {$:today}+' |
| Tue Jan 10 | '+Today is Day {$:today}+' |
| Thu Jan 12 | '+Today is Day {$:today}+' |
| Fri Jan 13 | '+Today is Day {$:today}+' |
| Tue Jan 17 | '+Today is Day {$:today}+' |
| Thu Jan 19 | '+Today is Day {$:today}+' |
| Fri Jan 20 | '+Today is Day {$:today}+' |
| Mon Jan 23 | '+Today is Day {$:today}+' |
| Tue Jan 24 | '+Today is Day {$:today}+' |
| Thu Jan 26 | '+Today is Day {$:today}+' |
| Fri Jan 27 | '+Today is Day {$:today}+' |
| Mon Jan 30 | '+Today is Day {$:today}+' |
| Tue Jan 31 | '+Today is Day {$:today}+' |
| Thu Feb 2 | '+Today is Day {$:today}+' |
| Fri Feb 3 | '+Today is Day {$:today}+' |
| Mon Feb 6 | '+Today is Day {$:today}+' |
| Tue Feb 7 | '+Today is Day {$:today}+' |
| Thu Feb 9 | '+Today is Day {$:today}+' |
| Fri Feb 10 | '+Today is Day {$:today}+' |
| Mon Feb 13 | '+Today is Day {$:today}+' |
| Tue Feb 14 | '+Today is Day {$:today}+' |
| Thu Feb 16 | '+Today is Day {$:today}+' |
| Fri Feb 17 | '+Today is Day {$:today}+' |
| Tue Feb 21 | '+Today is Day {$:today}+' |
| Thu Feb 23 | '+Today is Day {$:today}+' |
| Fri Feb 24 | '+Today is Day {$:today}+' |
| Mon Feb 27 | '+Today is Day {$:today}+' |
| Tue Feb 28 | '+Today is Day {$:today}+' |
| Thu Mar 2 | '+Today is Day {$:today}+' |
| Fri Mar 3 | '+Today is Day {$:today}+' |
| Mon Mar 6 | '+Today is Day {$:today}+' |
| Tue Mar 7 | '+Today is Day {$:today}+' |
| Thu Mar 9 | '+Today is Day {$:today}+' |
| Fri Mar 10 | '+Today is Day {$:today}+' |
| Mon Mar 13 | '+Today is Day {$:today}+' |
| Tue Mar 14 | '+Today is Day {$:today}+' |
| Thu Mar 16 | '+Today is Day {$:today}+' |
| Fri Mar 17 | '+Today is Day {$:today}+' |
| Mon Mar 20 | '+Today is Day {$:today}+' |
| Tue Mar 21 | '+Today is Day {$:today}+' |
| Thu Mar 23 | '+Today is Day {$:today}+' |
| Fri Mar 24 | '+Today is Day {$:today}+' |
| Mon Mar 27 | '+Today is Day {$:today}+' |
| Tue Mar 28 | '+Today is Day {$:today}+' |
| Thu Mar 30 | '+Today is Day {$:today}+' |
| Mon Apr 3 | !!Activity/Discussion  !!! Mathematical Modeling  >>toggle<< Deterministic Models >>indent<< When we study a relationship between quantities, we gather observations of the relationship. These |
| Tue Apr 4 | ! During class  !!Discussion/Activity !!!Gradient Descent with one variable *Mathematica Notebook example - https://github.com/bmwoodruff/m119-f21/blob/master/GradientDescent.nb *Q&A time *Implement a |
| Mon Apr 17 | '+Today is Day {$:today}+' |
| Tue Apr 18 | '+Today is Day {$:today}+' |
| Thu Apr 20 | '+Today is Day {$:today}+' |
| Fri Apr 21 | '+Today is Day {$:today}+' |
| Mon Apr 24 | '+Today is Day {$:today}+' |
| Tue Apr 25 | '+Today is Day {$:today}+' |
| Thu Apr 27 | '+Today is Day {$:today}+' |
| Fri Apr 28 | '+Today is Day {$:today}+' |
| Mon May 1 | '+Today is Day {$:today}+' |
| Tue May 2 | '+Today is Day {$:today}+' |
| Thu May 4 | '+Today is Day {$:today}+' |
| Fri May 5 | '+Today is Day {$:today}+' |
| Mon May 8 | '+Today is Day {$:today}+' |
| Tue May 9 | '+Today is Day {$:today}+' |
| Thu May 11 | '+Today is Day {$:today}+' |
| Fri May 12 | '+Today is Day {$:today}+' |
| Mon May 15 | '+Today is Day {$:today}+' |
| Tue May 16 | '+Today is Day {$:today}+' |
| Thu May 18 | '+Today is Day {$:today}+' |
| Fri May 19 | '+Today is Day {$:today}+' |
| Mon May 22 | '+Today is Day {$:today}+' |
| Tue May 23 | '+Today is Day {$:today}+' |
| Thu May 25 | '+Today is Day {$:today}+' |
| Fri May 26 | '+Today is Day {$:today}+' |
| Tue May 30 | '+Today is Day {$:today}+' |
| Wed May 31 | You can access June 1 by using the [[Jun->Schedule.20230601]] button below. |
| Thu Jun 1 | '+Today is Day {$:today}+' |
| Fri Jun 2 | '+Today is Day {$:today}+' |
| Mon Jun 5 | '+Today is Day {$:today}+' |
| Tue Jun 6 | '+Today is Day {$:today}+' |
| Thu Jun 8 | '+Today is Day {$:today}+' |
| Fri Jun 9 | '+Today is Day {$:today}+' |
| Mon Jun 12 | '+Today is Day {$:today}+' |
| Tue Jun 13 | '+Today is Day {$:today}+' |
| Thu Jun 15 | '+Today is Day {$:today}+' |
| Fri Jun 16 | '+Today is Day {$:today}+' |
| Tue Jun 20 | '+Today is Day {$:today}+' |
| Thu Jun 22 | '+Today is Day {$:today}+' |
| Fri Jun 23 | '+Today is Day {$:today}+' |
| Mon Jun 26 | '+Today is Day {$:today}+' |
| Tue Jun 27 | '+Today is Day {$:today}+' |
| Thu Jun 29 | '+Today is Day {$:today}+' |
| Fri Jun 30 | '+Today is Day {$:today}+' |
| Mon Jul 3 | Today is a project Work Day.  I won't take attendance.  Ethan and I will be in class to help with any issues you may have on projects. |
| Thu Jul 6 | '+Today is Day {$:today}+' |
| Fri Jul 7 | '+Today is Day {$:today}+' |
| Mon Jul 10 | '+Today is Day {$:today}+' |
| Tue Jul 11 | '+Today is Day {$:today}+' |
| Thu Jul 13 | !!Activity/Discussion  !!! Mathematical Modeling  >>toggle<< Deterministic Models >>indent<< When we study a relationship between quantities, we gather observations of the relationship. These |
| Fri Jul 14 | ! During class  !!Discussion/Activity !!!Gradient Descent with one variable *Mathematica Notebook example - https://github.com/bmwoodruff/m119-f21/blob/master/GradientDescent.nb *Q&A time *Implement a |
| Mon Jul 17 | Last day to submit project work.  Ethan will be there to discuss any questions you have related to the project.  You you have till Wednesday to complete any Knewton Alta assignments.   Thanks for a gr |
| Mon Sep 11 | '+Today is Day {$:today}+' |
| Tue Sep 12 | '+Today is Day {$:today}+' |
| Thu Sep 14 | '+Today is Day {$:today}+' |
| Fri Sep 15 | '+Today is Day {$:today}+' |
| Mon Sep 18 | '+Today is Day {$:today}+' |
| Tue Sep 19 | '+Today is Day {$:today}+' |
| Thu Sep 21 | '+Today is Day {$:today}+' |
| Fri Sep 22 | '+Today is Day {$:today}+' |
| Mon Sep 25 | '+Today is Day {$:today}+' |
| Tue Sep 26 | '+Today is Day {$:today}+' |
| Thu Sep 28 | '+Today is Day {$:today}+' |
| Fri Sep 29 | '+Today is Day {$:today}+' |
| Mon Oct 2 | '+Today is Day {$:today}+' |
| Tue Oct 3 | '+Today is Day {$:today}+' |
| Thu Oct 5 | '+Today is Day {$:today}+' |
| Fri Oct 6 | '+Today is Day {$:today}+' |
| Mon Oct 9 | '+Today is Day {$:today}+' |
| Tue Oct 10 | '+Today is Day {$:today}+' |
| Thu Oct 12 | '+Today is Day {$:today}+' |
| Fri Oct 13 | '+Today is Day {$:today}+' |
| Mon Oct 16 | '+Today is Day {$:today}+' |
| Tue Oct 17 | '+Today is Day {$:today}+' |
| Thu Oct 19 | '+Today is Day {$:today}+' |
| Fri Oct 20 | '+Today is Day {$:today}+' |
| Mon Oct 23 | '+Today is Day {$:today}+' |
| Tue Oct 24 | '+Today is Day {$:today}+' |
| Thu Oct 26 | '+Today is Day {$:today}+' |
| Fri Oct 27 | '+Today is Day {$:today}+' |
| Mon Oct 30 | '+Today is Day {$:today}+' |
| Tue Oct 31 | '+Today is Day {$:today}+' |
| Thu Nov 2 | '+Today is Day {$:today}+' |
| Fri Nov 3 | '+Today is Day {$:today}+' |
| Mon Nov 6 | '+Today is Day {$:today}+' |
| Tue Nov 7 | '+Today is Day {$:today}+' |
| Thu Nov 9 | '+Today is Day {$:today}+' |
| Fri Nov 10 | '+Today is Day {$:today}+' |
| Mon Nov 13 | '+Today is Day {$:today}+' |
| Tue Nov 14 | '+Today is Day {$:today}+' |
| Thu Nov 16 | '+Today is Day {$:today}+' |
| Fri Nov 17 | '+Today is Day {$:today}+' |
| Mon Nov 20 | '+Today is Day {$:today}+' |
| Tue Nov 21 | Today is a work day.  You can focus on getting Project 2 complete, or Project 3 Task 1, or completing Knewton Alta assignments.  I'll be in class to answer questions. |
| Mon Nov 27 | '+Today is Day {$:today}+' |
| Tue Nov 28 | Today is a work day.  You can focus on getting Project work complete, or completing Knewton Alta assignments.  I'll be in class to answer questions. |
| Wed Nov 29 | '+Today is Day {$:today}+' |
| Thu Nov 30 | '+Today is Day {$:today}+' |
| Fri Dec 1 | '+Today is Day {$:today}+' |
| Mon Dec 4 | '+Today is Day {$:today}+' |
| Tue Dec 5 | Today is a work day.  You can focus on getting Project work complete, or completing Knewton Alta assignments.  I'll be in class to answer questions. |
| Thu Dec 7 | '+Today is Day {$:today}+' |
| Fri Dec 8 | !!Activity/Discussion  !!! Mathematical Modeling  >>toggle<< Deterministic Models >>indent<< When we study a relationship between quantities, we gather observations of the relationship. These |
| Mon Dec 11 | ! During class  !!Discussion/Activity !!!Gradient Descent with one variable *Mathematica Notebook example - https://github.com/bmwoodruff/m119-f21/blob/master/GradientDescent.nb *Q&A time *Implement a |
| Mon Sep 15 | '+Today is Day {$:today}+' |
| Tue Sep 16 | '+Today is Day {$:today}+' |
| Thu Sep 18 | '+Today is Day {$:today}+' |
| Fri Sep 19 | '+Today is Day {$:today}+' |
| Mon Sep 22 | '+Today is Day {$:today}+' |
| Tue Sep 23 | '+Today is Day {$:today}+' |
| Thu Sep 25 | '+Today is Day {$:today}+' |
| Fri Sep 26 | '+Today is Day {$:today}+' |
| Mon Sep 29 | '+Today is Day {$:today}+' |
| Tue Sep 30 | '+Today is Day {$:today}+' |
| Thu Oct 2 | '+Today is Day {$:today}+' |
| Fri Oct 3 | '+Today is Day {$:today}+' |
| Mon Oct 6 | '+Today is Day {$:today}+' |
| Tue Oct 7 | '+Today is Day {$:today}+' |
| Thu Oct 9 | '+Today is Day {$:today}+' |
| Fri Oct 10 | '+Today is Day {$:today}+' |
| Mon Oct 13 | '+Today is Day {$:today}+' |
| Tue Oct 14 | '+Today is Day {$:today}+' |
| Thu Oct 16 | '+Today is Day {$:today}+' |
| Fri Oct 17 | '+Today is Day {$:today}+' |
| Mon Oct 20 | '+Today is Day {$:today}+' |
| Tue Oct 21 | '+Today is Day {$:today}+' |
| Thu Oct 23 | '+Today is Day {$:today}+' |
| Fri Oct 24 | '+Today is Day {$:today}+' |
| Mon Oct 27 | '+Today is Day {$:today}+' |
| Tue Oct 28 | '+Today is Day {$:today}+' |
| Thu Oct 30 | '+Today is Day {$:today}+' |
| Fri Oct 31 | '+Today is Day {$:today}+' |
| Mon Nov 3 | '+Today is Day {$:today}+' |
| Tue Nov 4 | '+Today is Day {$:today}+' |
| Thu Nov 6 | '+Today is Day {$:today}+' |
| Fri Nov 7 | '+Today is Day {$:today}+' |
| Mon Nov 10 | '+Today is Day {$:today}+' |
| Tue Nov 11 | '+Today is Day {$:today}+' |
| Thu Nov 13 | '+Today is Day {$:today}+' |
| Fri Nov 14 | '+Today is Day {$:today}+' |
| Mon Nov 17 | '+Today is Day {$:today}+' |
| Tue Nov 18 | Project work day.  Come work on your project, or KnewtonAlta.  I'll be there to answer questions and help with whatever you want to work on. |
| Thu Nov 20 | '+Today is Day {$:today}+' |
| Fri Nov 21 | '+Today is Day {$:today}+' |
| Mon Nov 24 | '+Today is Day {$:today}+' |
| Tue Nov 25 | Today is another project work day. |
| Thu Nov 27 | Enjoy Thanksgiving! |
| Fri Nov 28 | Enjoy Thanksgiving! |
| Mon Dec 1 | '+Today is Day {$:today}+' |
| Tue Dec 2 | '+Today is Day {$:today}+' |
| Thu Dec 4 | '+Today is Day {$:today}+' |
| Fri Dec 5 | '+Today is Day {$:today}+' |
| Mon Dec 8 | '+Today is Day {$:today}+' |
| Tue Dec 9 | '+Today is Day {$:today}+' |
| Thu Dec 11 | '+Today is Day {$:today}+' |
| Fri Dec 12 | !!Activity/Discussion  !!! Mathematical Modeling  >>toggle<< Deterministic Models >>indent<< When we study a relationship between quantities, we gather observations of the relationship. These |
| Mon Dec 15 | ! During class  !!Discussion/Activity !!!Gradient Descent with one variable *Mathematica Notebook example - https://github.com/bmwoodruff/m119-f21/blob/master/GradientDescent.nb *Q&A time *Implement a |
| Thu Jan 8 | '+Today is Day {$:today}+' |
| Fri Jan 9 | '+Today is Day {$:today}+' |
| Mon Jan 12 | '+Today is Day {$:today}+' |
| Tue Jan 13 | '+Today is Day {$:today}+' |
| Thu Jan 15 | '+Today is Day {$:today}+' |
| Fri Jan 16 | '+Today is Day {$:today}+' |
| Tue Jan 20 | '+Today is Day {$:today}+' |
| Thu Jan 22 | '+Today is Day {$:today}+' |
| Fri Jan 23 | '+Today is Day {$:today}+' |
| Mon Jan 26 | '+Today is Day {$:today}+' |
| Tue Jan 27 | '+Today is Day {$:today}+' |
| Thu Jan 29 | '+Today is Day {$:today}+' |
| Fri Jan 30 | '+Today is Day {$:today}+' |
| Mon Feb 2 | '+Today is Day {$:today}+' |
| Tue Feb 3 | '+Today is Day {$:today}+' |
| Thu Feb 5 | '+Today is Day {$:today}+' |
| Fri Feb 6 | '+Today is Day {$:today}+' |
| Mon Feb 9 | '+Today is Day {$:today}+' |
| Tue Feb 10 | '+Today is Day {$:today}+' |
| Thu Feb 12 | '+Today is Day {$:today}+' |
| Fri Feb 13 | '+Today is Day {$:today}+' |
| Tue Feb 17 | '+Today is Day {$:today}+' |
| Wed Feb 18 | I gave a presentation to another class about cryptography, along with an introduction to some topics in geometric group theory and homotopy theory.   * https://bmwoodruff.github.io/path-loops-secrets/ |
| Thu Feb 19 | '+Today is Day {$:today}+' |
| Fri Feb 20 | '+Today is Day {$:today}+' |
| Mon Feb 23 | '+Today is Day {$:today}+' |
| Tue Feb 24 | Project Work day. Come get help on your projects, finish up KnewtonAlta, etc. |
| Thu Feb 26 | '+Today is Day {$:today}+' |
| Fri Feb 27 | '+Today is Day {$:today}+' |
| Mon Mar 2 | '+Today is Day {$:today}+' |
| Tue Mar 3 | '+Today is Day {$:today}+' |
| Thu Mar 5 | '+Today is Day {$:today}+' |
| Fri Mar 6 | '+Today is Day {$:today}+' |
| Mon Mar 9 | '+Today is Day {$:today}+' |
| Tue Mar 10 | '+Today is Day {$:today}+' |
| Thu Mar 12 | '+Today is Day {$:today}+' |
| Fri Mar 13 | '+Today is Day {$:today}+' |
| Mon Mar 16 | '+Today is Day {$:today}+' |
| Tue Mar 17 | '+Today is Day {$:today}+' |
| Thu Mar 19 | '+Today is Day {$:today}+' |
| Fri Mar 20 | '+Today is Day {$:today}+' |
| Mon Mar 23 | '+Today is Day {$:today}+' |
| Tue Mar 24 | '+Today is Day {$:today}+' |
| Thu Mar 26 | '+Today is Day {$:today}+' |
| Fri Mar 27 | Today is a Project Work day. |
| Mon Mar 30 | '+Today is Day {$:today}+' |
| Tue Mar 31 | '+Today is Day {$:today}+' |
| Thu Apr 2 | '+Today is Day {$:today}+' |
| Fri Apr 3 | '+Today is Day {$:today}+' |
| Mon Apr 6 | !!Activity/Discussion  !!! Mathematical Modeling  >>toggle<< Deterministic Models >>indent<< When we study a relationship between quantities, we gather observations of the relationship. These |
| Tue Apr 7 | ! During class  !!Discussion/Activity !!!Gradient Descent with one variable *Mathematica Notebook example - https://github.com/bmwoodruff/m119-f21/blob/master/GradientDescent.nb *Q&A time *Implement a |
| Mon Apr 20 | '+Today is Day {$:today}+' |
| Tue Apr 21 | '+Today is Day {$:today}+' |
| Thu Apr 23 | '+Today is Day {$:today}+' |
| Fri Apr 24 | '+Today is Day {$:today}+' |
| Mon Apr 27 | '+Today is Day {$:today}+' |
| Mon Apr 27 | Project Work day.  I'll be in Utah giving the banquet talk at the 2026 conference for the Intermountain section of the MAA. |
| Tue Apr 28 | '+Today is Day {$:today}+' |
| Thu Apr 30 | '+Today is Day {$:today}+' |
| Fri May 1 | '+Today is Day {$:today}+' |
| Mon May 4 | '+Today is Day {$:today}+' |
| Tue May 5 | '+Today is Day {$:today}+' |
| Thu May 7 | '+Today is Day {$:today}+' |
| Fri May 8 | '+Today is Day {$:today}+' |
| Mon May 11 | '+Today is Day {$:today}+' |
| Tue May 12 | '+Today is Day {$:today}+' |
| Thu May 14 | '+Today is Day {$:today}+' |
| Fri May 15 | '+Today is Day {$:today}+' |
| Mon May 18 | '+Today is Day {$:today}+' |
| Tue May 19 | '+Today is Day {$:today}+' |
| Thu May 21 | '+Today is Day {$:today}+' |
| Fri May 22 | '+Today is Day {$:today}+' |
| Mon May 25 | No class today — Memorial Day. |
| Tue May 26 | '+Today is Day {$:today}+' |
| Thu May 28 | '+Today is Day {$:today}+' |
| Fri May 29 | '+Today is Day {$:today}+' |
| Mon Jun 1 | '+Today is Day {$:today}+' |
| Tue Jun 2 | '+Today is Day {$:today}+' |
| Thu Jun 4 | '+Today is Day {$:today}+' |
| Fri Jun 5 | '+Today is Day {$:today}+' |
| Mon Jun 8 | '+Today is Day {$:today}+' |
| Tue Jun 9 | '+Today is Day {$:today}+' |
| Thu Jun 11 | '+Today is Day {$:today}+' |
| Fri Jun 12 | '+Today is Day {$:today}+' |
| Mon Jun 15 | '+Today is Day {$:today}+' |
| Tue Jun 16 | '+Today is Day {$:today}+' |
| Thu Jun 18 | '+Today is Day {$:today}+' |
| Fri Jun 19 | No class today — Juneteenth. |
| Mon Jun 22 | '+Today is Day {$:today}+' |
| Tue Jun 23 | '+Today is Day {$:today}+' |
| Thu Jun 25 | '+Today is Day {$:today}+' |
| Fri Jun 26 | '+Today is Day {$:today}+' |
| Mon Jun 29 | '+Today is Day {$:today}+' |
| Tue Jun 30 | '+Today is Day {$:today}+' |
| Thu Jul 2 | '+Today is Day {$:today}+' |
| Fri Jul 3 | No class today — Independence Day. |
| Mon Jul 6 | '+Today is Day {$:today}+' |
| Tue Jul 7 | '+Today is Day {$:today}+' |
| Thu Jul 9 | '+Today is Day {$:today}+' |
| Fri Jul 10 | '+Today is Day {$:today}+' |
| Mon Jul 13 | '+Today is Day {$:today}+' |
| Mon Jul 20 | Today is a Project Work Day. Come work on your project or Knewton Alta. I'll be in class to answer questions. |
| Tue Jul 21 | Today is a Project Work Day. Come work on your project or Knewton Alta. I'll be in class to answer questions. |
