---
title: "Project 3 Instructions"
author: ""
date: "Updated "
output: html_document
---

ADD SPECS LIST HERE

ADD BACKGROUND INFORMATION HERE

In Project 3 template includes background for the data and questions we will be exploring. To complete this project you will need to complete the following tasks insuring that you meet **ALL** the specifications. If **any** of the specifications are not met you will receive feedback identifying the specification(s) that still require work in order to complete the project.

## Project Outline
### Focus on the Data

- **Task 1a:** Create a histogram of the data. 
(BE EXPLICIT, what data? what measurements?)

- **Task 1b:** Calculate the sample mean and the sample standard deviation for the data.
LINK to ?mean and ?sd documentation pages.


### Focus on the Model (a family of models)
Consider the probability (density) model, [INSERT A SVG of the equation]
$$f_1(x) = \frac{\lambda^r}{\Gamma(r)}x^{r-1}e^{-\lambda x}$$ with $x \geq 0$, $r>0$, and $\lambda > 0$. This is called the gamma distribution. 

- **Task 2a:** Experiement with different values of parameters and pay attention to how changing the parameters of the model (or distribution) changes the behavior of the model (or distribution or density function). Plot the distribution for at least three choices of the parameters.  Make sure you clearly indicate which parameter values you used in each plot. Summarize (describe) what you learned about the effect of each parameter on the behavior of the function referencing specific features in your plots. 	

- **Task 2b:** Calculate the mean and standard deviation of the model (or distribution) as a function of the parameters using Mathematica.
Tell students to use the code from class.

### Select and Use a Model (from the Family)

- **Task 3:** Estimate the values of the parameters using the given data. Write down the system of equations you need to solve using the sample mean, sample standard deviation, and the mean and standard deviation of the distribution as functions of the parameters. Solve the system of equations.

- Simulate data using the specific model (give the parameter values you found) and compare the simulated data with the real data. 
(We want students to see that a probability model can be explored in more ways than just a graph of the density or corresponding CDF.)

    - **Task 4a:**[ADD: USE THE FOLLOWING CODE with the parameter values you found that fit the data] to create a sample of 2500 random measurements using the model.

    - **Task 4b:** Plot a histogram of your simulated data.

    - **Task 4c:** Calculate the sample mean and sample standard deviation of your simulated data. 
    
    - **Task 4d:** How does the sample mean and sample standard deviation of yoru simulated data compare with the sample mean and sample standard deviation of the real data?

- **Task 5:** Answer the following questions using the appropriate probability calculations.

    1. What is the probability that the amount of explosive in a sample will be between 0.1 and 0.3? Write down the integral you need to calculate and then compute the value.
  
    2. What is the probability that the amount of explosive in a sample will be more than 0.5? Write down the integral you need to calculate and then compute the value.

    3. What is the 90$^{\text{th}}$ percentile of the distribution? Write down the equation you need to solve, it will include an integral, and then solve the equation.


### A Model is an Assumption
- **Task 6a:** In class we completed Task 2, Task 3, and Task 5 for $f_2(x) = \frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{1}{2}(\frac{x-\mu}{\sigma})^2}$ with $-\infty < x < \infty$, $\mu > 0$, and $\sigma > 0$. This is called the normal distribution. Repeat Task 2, Task 3, and Task 5 for $f_4(x) = \frac{1}{b-a}$ with $a < x < b$ and $-\infty < a < b <\infty$. This is called the uniform distribution.

- **Task 6b:** How do the probabilities calculated in Task 5 depend on the assumption made about which general model (distribution with unknown parameters) is used? Which distribution shape (gamma, $f_1$; normal, $f_2$; or uniform, $f_4$) do you think best describes the given data? Make sure to provide support for your answer. 


### Conclusions

- **Task 7:** Answer the question, "Does the soil in this area meet [a specified requirement]?" Make sure to provide support for your conclusion. 


### Reflection

- **Task 8:** Reflect on your work for this project. In 1-2 paragraphs, identify/explain 2-3 key mathematical  ideas you learned (and would like to remember) and 1-3 soft skills you needed/improved/learned while working on the project.

## Template File
- [Project 3 .Rmd template](project3_template.Rmd)