---
title: "Calculus Reference Sheet"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---

## Derivative Rules:

#### Power Rule
+ 
$\frac{d}{dx}(x^n) = nx^{n-1}$ where $n$ is any real number. 

#### $e^x$ Rule
+ 
$\frac{d}{dx}(e^x) = e^x$

#### Natural Logarithm Rule
+ 
$\frac{d}{dx}(\ln(x)) = \frac{1}{x}$ where $x > 0$

#### Exponential Rule
+ 
$\frac{d}{dx}(b^x) = b^x\ln(b)$ where $b > 0$ and $b \neq 1$

#### Logarithm Rule
+ 
$\frac{d}{dx}(\log_b(x)) = \frac{1}{x\ln(b)}$ where $x > 0$, $b > 0$, and $b \neq 1$

#### Constant Multiple Rule
+ 
$\frac{d}{dx}(cf(x)) = c\frac{d}{dx}(f(x))$ where $c$ is a real number. 

#### Sum and Difference Rule
- $\frac{d}{dx}(f(x) \pm g(x)) = \frac{d}{dx}(f(x)) \pm \frac{d}{dx}(g(x))$ 
    - $\frac{d}{dx}(f(x) + g(x)) = \frac{d}{dx}(f(x)) + \frac{d}{dx}(g(x))$
    - $\frac{d}{dx}(f(x) - g(x)) = \frac{d}{dx}(f(x)) - \frac{d}{dx}(g(x))$

#### Product Rule
+ 
$\frac{d}{dx}(f(x)g(x)) = (\frac{df}{dx}(x))g(x) + f(x)\frac{dg}{dx}(x)$

#### Quotient Rule
+ 
$\frac{d}{dx}\left(\frac{f(x)}{g(x)}\right) = \frac{(\frac{df}{dx}(x))g(x) - f(x)\frac{dg}{dx}(x)}{(g(x))^2}$

#### Chain Rule
+ $\frac{d}{dx}(f(g(x))) = \frac{df}{dg}\frac{dg}{dx}$
    + Given $h(x) = f(g(x))$, $h'(x) = f'(g(x))g'(x)$. 



## Definition of Logarithm:
+ 
For $x>0$, $b>0$, and $b\neq 1$, $y = \log_b(x)$ is equivalent to $b^y=x$



## Properties of Logarithms: 

#### Product Property
+ 
$\log_b(ac) = \log_b(a) + \log_b(c)$

#### Quotient Property
+ 
$\log_b\left(\frac{a}{c}\right) = \log_b(a) - \log_b(c)$

#### Power Property
+ 
$\log_b(a^n) = n\log_b(a)$



## Properties of Sums: 
+ 
$\sum_{i=1}^{n}c = n c$
+ 
$\sum_{i=1}^{n}c a_i = c\sum_{i=1}^{n}a_i$

+ $\sum_{i=1}^{n}a_i \pm b_i = \sum_{i=1}^{n}a_i \pm \sum_{i=1}^{n}b_i$
    + $\sum_{i=1}^{n}a_i + b_i = \sum_{i=1}^{n}a_i + \sum_{i=1}^{n}b_i$
    + $\sum_{i=1}^{n}a_i - b_i = \sum_{i=1}^{n}a_i - \sum_{i=1}^{n}b_i$

