---
title: "Specs List"
author: ""
date: "Updated Dec 22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Specs List
- Project is ready for review.
- Cohesive analysis provided.
- Work is reproducible.
- Mathematical notation and terminology is used correctly or with only minor errors.
- Calculations and plots are correct or have only minor errors.

If **any** of the specifications are not met you will receive an incomplete and feedback identifying at least one specification that still requires work in order to complete the project.




This outline provides you a structure as you create plots and work through calculations relevant to the question described in the background information above. Make sure you meet **ALL** the specifications (General Specs and Project Standards listed above). If **any** of the specifications are not met you will receive an incomplete and feedback identifying at least one specification that still requires work in order to complete the project.

## Specs List
- General Specs
    - Project is ready for review. (**separate doc dealing with ambiguity -- expounding -- giving examples and nonexamples**)
        - Instructions followed.
        - Good faith effort evident for all tasks. (Define Good Faith effort) 
        - The writing is almost free, if not entirely free, of distracting spelling or grammatical errors (incomplete sentences, subject-verb disagreement, and misuse of punctuation). -- I think this spec belongs in a different category (Maybe presentation???)
    - Provide a Cohesive Analysis. (**separate doc dealing with ambiguity -- expounding -- giving examples and nonexamples**)
        - All calculations are introduced with complete sentences (and paragraphs). Remember introductions come BEFORE the calculation, tell your reader what is coming.
        - All plots are introduced with complete sentences (and paragraphs). Remember introductions come BEFORE the plot, tell your reader what is coming.
        - All calculations are explained, interpreted, and described using complete sentences (and paragraphs). Explanations can come before or after a plot, tell your reader what is important what they should notice. Make connections and transitions.
        - All plots are explained, interpreted, and described using complete sentences (and paragraphs). Explanations can come before or after a plot, tell your reader what is important what they should notice. Make connections and transitions.
        - transitions
        - a person can read the analysis without ever seeing the instructions for the assignment and know what is going on
    - Work is reproducible.(**separate doc dealing with ambiguity -- expounding -- giving examples and nonexamples**)
        - Enough steps of calculations included so that thinking can be traced.
        - R code is included in html submission with hide/show button.
        - Mathematica code and output is included (you can insert a picture).
    - Mathematical notation and terminology is used properly with only minor revisions need.
    - The work was completed by the student. (**NOT a spec put in the Canvas assignment instructions** This is hard for me to really evaluative -- but maybe a good reminder for students -- Include a reminder about citing work from in class, colleagues, internet, ... -- informal citation conventions??? -- Put in Canvas)
    - Calculations and plots are correct (spot check when reviewing)
        - Student check work before submitting.
        

- Project Standards (Project 1)
(Maybe don't have these??? Although this semester they are the easier thing to check, especially when I provide solutions)
    - Demonstrates ability to create scatter plots in R and the required scatter plot is correct.
    - Demonstrates ability to plot functions in R and the required plots are correct.
    - Demonstrates ability to solve equations using R and the solutions are correct.
    - Demonstrates ability to solve simple equations analytically and the solutions are correct.
    - Demonstrates ability to plot density histograms in R and the require histogram is correct.
    - Demonstrates the ability to visually fit a model to data by selecting paramter values and the visual fit look reasonable.
    - Demonstrates the ability to use a fitted model to answer questions or provide predictions and the answers presented are reasonable, consistent, and correct.
    - Demonstrates understanding that the information we learn from our data depends on the general model we assume.
    - Demonstrates understanding about the different between deterministic models and stochastic models.




- Project Standards (Project 2)
    - Demonstrates understanding of sum notation and almost all, if not all, the requested sums are expanded correctly.
    - Demonstrates ability to calculate statistics using R (given a formula and data) and almost all, if not all, the requested statistics are correctly calculated.
    - Demonstrates an understanding of the concept of a loglikelihood function by providing the correct formulas for the loglikelihood functions specified ($f_6$ and $f_5$.
    - Demonstrates ability to find a partial derivative and the required partial derivatives are correct.
    - Demonstrates ability to solve systems of equations ~~using R~~ and the solutions are correct.
    - Demonstrates ability to plot functions in R and the required plots of the fitted models show at least a visual fit to the data.
    - Demonstrates the ability to use a (fitted) model to answer questions about data and the answers presented are reasonable, consistent, and correct.
    - Demonstrates understanding that the information we identify using our data depends on which model (or function family, for example $f_6$ or $f_5$ ~~$f$, $f_0$, $f_1$ or $f_2$~~) we assume describes the relationship seen in the data and this understanding is demonstrated by an relevant and consistent comparison. 
    
    
    
- Project Standards (Project 3)
    - Demonstrates ability to plot density histograms in R and the require histograms are correct.
    - Demonstrates ability to calculate means and standard deviation in R and the values for means and standard deviations are correct.
    - Demonstrates understanding of the relationship between models and parameters and the summary of parameter exploration is reasonable, consistent, and correct.
    - Demonstrates the ability to use Mathematica to compute definite integrals and the solutions are correct.
    - Demonstrates the ability to solve systems of equations and the solutions are correct.
    - Demonstrates the ability to use the distribution function in R to create a simulated sample and the sample is created correctly.
    - Demonstrates ability to calculate probability and percentiles and the solutions are correct.
    - Demonstrates understanding that the information we identify from measurement data depends on our assumption of which model (or distribution) we use and this understanding is demonstrated by an relevant and consistent comparison.