---
title: "Project Specs"
author: ""
date: "Updated Dec 22"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Specs List
- Project is ready for review.
- Cohesive analysis provided.
- Work is reproducible.
- Mathematical notation and terminology is used correctly or with only minor errors.
- Calculations and plots are correct or have only minor errors.

If you submit an assignment that is not ready for review: I will mark it "Unacceptable" in the rubric (and "Incomplete" in the assignment grade). You will not be able to revise and resubmit the assignment. I will not not provide feedback on any of the other specs for that assignment.

The list of specifications (or specs) below describe how your assignment will be evaluated. Your work must satisfy **all** the specs, otherwise, you will receive an "Incomplete". If you receive an "Incomplete" (and your assignment was ready for review) you can revise and resubmit. The number of resubmissions is limited to once per week (and the end of the semester).