---
title: "Class 7"
---
# Between Class Sessions - Prep for Day 7 <a id="tasklist"></a>

<!-- from Prep.GeneralInstructions -->
Please spend around 2 hours working between class sessions, focusing on the tasks below. Use any extra time to complete KnewtonAlta assignments and/or work on Project tasks. 

Pick something from your prep today that you can share with your group in class. It might be something new that you learned. It might be questions you have that are still unanswered, or a question along with what helped you eventually answer it. It might be something tricky that you solved. It might be a review topic that helped you remember something.  It might be a conversation you had with AI that was helpful. You will have a chance to share this with your peers during class. Come ready to articulate your thinking and questions.

<a id="Prep"></a>

## Preparation

### (1) Describing Functions (practice Reading Mathematics)
Click on each box to expand it. Read each of the definitions. Then complete the questions that follow. 

<details>
<summary>Definition: **Constant** on the Interval $I$</summary>

We say a function $f$ is constant on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) = f(x_2)$.

</details>

<details>
<summary>Definition: **Increasing** on the Interval $I$ (from OpenStax textbook)</summary>

We say a function $f$ is increasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) \leq f(x_2)$ when $x_1 < x_2$.

Note: We say a function $f$ is strictly increasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) < f(x_2)$ when $x_1 < x_2$.

</details>

<details>
<summary>Definition: **Decreasing** on the Interval $I$ (from OpenStax textbook)</summary>

We say a function $f$ is decreasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) \geq f(x_2)$ when $x_1 < x_2$.

Note: We say a function $f$ is strictly decreasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) > f(x_2)$ when $x_1 < x_2$.

</details>

<details>
<summary>Definition: **Positive** on the interval $I$</summary>

We say a function $f$ is positive on the interval $I$ if for all $x_1$ in the interval, $f(x_1) > 0$.

</details>

<details>
<summary>Definition: **Nonnegative** on the interval $I$</summary>

We say a function $f$ is nonnegative on the interval $I$ if for all $x_1$ in the interval, $f(x_1) \geq 0$.

</details>

<details>
<summary>Definition: **Negative** on the interval $I$</summary>

We say a function $f$ is negative on the interval $I$ if for all $x_1$ in the interval, $f(x_1) < 0$.

</details>

- What is the difference between a function being positive and a function being nonnegative?
- Give an example of a function that is constant and nonnegative on the interval $ (1,5) $. 
- Give an example of a function that is negative and strictly increasing on the interval $ (0,2) $
- Can a function be both positive and nonnegative on an interval? If so, give an example. 
- Can a function be both increasing and decreasing on an interval? If so, give an example. 
- Give an example of a positive function that is increasing on $ (-2,0) $ and then decreasing on $ (0,2) $.

### (2) Sum and Product Notation

**Sum Notation**<br>
The symbol $\sum_{k=1}^n a_k$ means to find the sum of the $a_k$ terms for each integer from $k=1$ to $k=n$ .

For example:

- $\sum_{k=2}^5 (3k-1) = \underbrace{ (3(2)-1) }_{k=2} + \underbrace{ (3(3)-1) }_{k=3}  + \underbrace{ (3(4)-1) }_{k=4} +\underbrace{ (3(5)-1) }_{k=5} = 5+8+11+14 =  38$.

**Product Notation**<br>
The symbol $\prod_{j=1}^n a_j$ means to find the product of the $a_j$ terms for each integer from $j=1$ to $j=n$.

For example:

- $\prod_{m=2}^5 (3m-1) = \underbrace{ (3(2)-1) }_{k=2}\cdot \underbrace{ (3(3)-1) }_{k=3}\cdot \underbrace{ (3(4)-1) }_{k=4}\cdot \underbrace{ (3(5)-1) }_{k=5} = 5\cdot 8\cdot 11\cdot 14=6160$.

We can use R to compute sums and products as follows. 

```r
k <- seq(2,5)
sum(3*k-1)
prod(3*k-1)
```

Calculate the following values by hand, and check your work with R. 

- $\sum_{m=1}^5 (4m^2+4)$ and $\prod_{m=1}^5 (4m^2+4)$
- $\sum_{k=1}^4 (30 - k^2)$ and $\prod_{k=1}^3 (30 - k^2)$
- $\sum_{n=1}^{10} n$ and $\prod_{n=1}^7 n$
- $\sum_{i=1}^6 (50-i)$ and $\prod_{i=1}^6 (10-i)$

### (3) Systems of Equations (videos)
Watch the following videos about solving systems of equations.

- [Video 1](https://www.youtube.com/watch?v=HxhacvH49o8) (~10 minutes)
- [Video 2](https://www.youtube.com/watch?v=ova8GSmPV4o) (~7.5 minutes)

<a id="PP"></a>

## Regular Reminders
### Skill Practice (KA Homework)
- Complete 1 -- Transformations of Functions assignment
- Complete 1 -- Solving Linear Systems assignment 

### Applied Practice (Project Work)
- Continue working on Project 1 Task 2


# During Class - Day 7
## Brain Gains
Write in expanded form and then calculate each of the following.

1. $\sum_{k=4}^{8} (5-k)$

1. $\prod_{n=1}^4 n$
1. $\frac{1}{3}\sum_{i=3}^{7} (2+i^2)$
When you finish, check your solution using R.

<details>
<summary>Solution</summary>

- We find $\sum_{k=4}^{8} (5-k) = (5-4) + (5-5) + (5-6) + (5-7) + (5-8) = -5$.

```r
x <- c(4,5,6,7,8)
sum(5-x)
```

- We compute $\prod_{n=1}^4 n = 1(2)(3)(4) = 24$. 

```r
prod(1:4)
```

Since $4! = \prod_{n=1}^4 n$, you can also use the factorial command in R to commute this product.

```r
factorial(4)
```

- We see $\frac{1}{3}\sum_{i=3}^{7} (2+i^2) = \frac{1}{3}\left( (2+3^2) + (2+4^2) + (2+5^2) + (2+6)^2 + (2+7^2)\right) = \frac{145}{3}.$

```r
i <- 3:7
sum((2+i^2))
sum((2+i^2))/3
```

</details>

## Group Meeting 
Start by giving each person a moment to share what they chose to prepare for class. Help each other address any questions.  When each person has had a chance to share, move on the other activities.

### Describing Functions (practice Reading Mathematics)
The prep for yesterday involved reading and coming up with examples related to 6 definitions. 

<!-- from Definition.ConstantOnTheIntervalI -->
<details>
<summary>Definition: **Constant** on the Interval $I$</summary>

We say a function $f$ is constant on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) = f(x_2)$.

</details>

<!-- from Definition.IncreasingOnTheIntervalI -->
<details>
<summary>Definition: **Increasing** on the Interval $I$ (from OpenStax textbook)</summary>

We say a function $f$ is increasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) \leq f(x_2)$ when $x_1 < x_2$.

Note: We say a function $f$ is strictly increasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) < f(x_2)$ when $x_1 < x_2$.

</details>

<!-- from Definition.DecreasingOnTheIntervalI -->
<details>
<summary>Definition: **Decreasing** on the Interval $I$ (from OpenStax textbook)</summary>

We say a function $f$ is decreasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) \geq f(x_2)$ when $x_1 < x_2$.

Note: We say a function $f$ is strictly decreasing on the interval $I$ if for all $x_1$ and $x_2$ in the interval, $f(x_1) > f(x_2)$ when $x_1 < x_2$.

</details>

<!-- from Definition.PositiveOnTheIntervalI -->
<details>
<summary>Definition: **Positive** on the interval $I$</summary>

We say a function $f$ is positive on the interval $I$ if for all $x_1$ in the interval, $f(x_1) > 0$.

</details>

<!-- from Definition.NonnegativeOnTheIntervalI -->
<details>
<summary>Definition: **Nonnegative** on the interval $I$</summary>

We say a function $f$ is nonnegative on the interval $I$ if for all $x_1$ in the interval, $f(x_1) \geq 0$.

</details>

<!-- from Definition.NegativeOnTheIntervalI -->
<details>
<summary>Definition: **Negative** on the interval $I$</summary>

We say a function $f$ is negative on the interval $I$ if for all $x_1$ in the interval, $f(x_1) < 0$.

</details>

Let's apply these definitions to some examples. 

1. Consider the function $\ds f(x) = \begin{cases}-x-4 & x<-2\\-2 & -2\leq x\leq 2\\x-4 & 2<x\\\end{cases}.$
    1. Sketch the graph of $f$.
    1. Give an interval on which $f$ is constant. Then give another. 
    1. Give an interval on which $f$ is increasing.  Then give another. 
    1. Give an interval on which $f$ is decreasing.  Then give another. 
    1. Give an interval on which $f$ is positive.  Then give another. 
    1. Give an interval on which $f$ is non-negative.  Then give another. 
    1. Give an interval on which $f$ is negative.  Then give another. 
    1. Give an interval on which $f$ is both increasing and decreasing. 
1. Draw the graph of a function that  is constant on $ (0,2) $, strictly increasing on $ (2,5) $, decreasing on $ (5,10) $, nonnegative on $ [4,7] $, and negative on both $ [0,4) $ and $ (7,10] $.

### Sum and Product Notation
Start by discussing any questions from the prep. The complete the following with your team. 

1. Writing the expression in expanded form, then compute the sum or product, and finish by checking with R. 
    1.  $\sum_{k=2}^{4} (2k-3)$
    1. $\prod_{k=2}^4 (2k-3)$
    1. $\sum_{k=3}^{8} (k-5)^2$
    1. $\prod_{n=3}^8 (n-5)^2$
1. Write out each sum in expanded form (or at least show the pattern), and then use R to compute the sum. 
    1.  $\sum_{k=1}^{1} (2k-1)$
    1. $\sum_{k=1}^{2} (2k-1)$
    1. $\sum_{k=1}^{3} (2k-1)$
    1. $\sum_{k=1}^{4} (2k-1)$
    1. $\sum_{k=1}^{5} (2k-1)$
    1. $\sum_{k=1}^{6} (2k-1)$
1. Make a guess, based on the patterns from above, for $\sum_{k=1}^{20} (2k-1)$. Then check with R. 

1. Compute $1+3+5+\cdots+97+99$.

### Systems of Equations (videos)
Solve each system of equations for $x$ and $y$. The variables $a,b,c,d,e,f$ below are constants. 

- $3x + 2y = -4, -x + 7y = 9$
- $x+2y=3, 4x+5y=6$
- $x+by=3, 4x+5y=6$
- $x+by=c, 4x+5y=6$
- $x+by=c, dx+5y=6$
- $x+by=c, dx+ey=6$
- $x+by=c, dx+ey=f$
- $ax+by=c, dx+ey=f$

## Discussion
- Reminder of what the parameters in the general transformation form do.
$$ T(x) = af(b(x-h))+k $$

- Let's think about the general quadratic $f(x) = a_2x^2 + a_1x + a_0$.
    - Recall the example. $q(x) = x^2 + 4x + 9$. We wrote $q(x) = (x-2)^2+5$ by completing the square.
    - Consider $g(x) = x^2 - 5x - 1$ or $h(x) = 2x^2 + 14x + 3$. 
      - $g(x) = (x - \frac{5}{2})^2 - \frac{29}{4}$
      - $h(x) = 2(x + \frac{7}{2})^2 - \frac{86}{4}$
    - Open the [Desmos](https://www.desmos.com/calculator/sfm0h6cq1f){target="_blank"}.

## Discussion - Project 1 Task 2 and the Example Project. 
If you haven't yet found the worked examples in Canvas, note that there are examples for a few tasks in the Additional resources module. Here is an example for project 1 task 2, which shows how you can put multiple plots together in the same figure, using the par(mfrow()) command, something required for the task.  Note that the example below shows far more plots than are required for the actual tasks.   

- [Project 1 Task 2 worked example](https://chaz-clark.github.io/M119/Projects/m119-docs/Project1_Task2_f2_example.html)

We'll spend the rest of class examining the example project's Task 2. 

- Open the [Example Project Instructions](../assets/docs/example_project.html){target="_blank"}, and briefly read Task 2
- Use the Desmos links to explore the three probability density models $f_0$, $f_1$, and $f_2$.
    - Use the slider to alter the values of $a$ and $b$. Discuss how these parameters alter the graph of $f_0$.
    - Use the slider to alter the values of $h$ and $a$. Discuss how these parameters alter the graph of $f_1$.
    - Use the slider to alter the values of $h$, $a$, and $b$. Discuss how these parameters alter the graph of $f_2$.

We'll have a discussion in class about what you observed.  
Our goal is to understand enough about the general functions $f_0$, $f_1$, and $f_2$ and their parameters to be able to identify specific functions (so specified parameters) of the forms $f_0$, $f_1$, and $f_2$ that looks like the density histogram of our light bulb data.  The code below will regenerate this histogram for us. 

```r
library(data4led)
dist <- led_time(2100)
hist(dist$percent_intensity,probability = TRUE)
```

If we have time today, we'll make a summary plot using the par(mfrow()) command to show what we learned. 

```r
rm(list=ls())
f0 <- function(x,a=0,b=1){
  # Make sure a < b when using this function.
  ifelse(x < a,NaN, ifelse(x <= b, 1/(b-a), NaN))
}

a <- 98
b <- 102
x <- seq(a,b,0.1)
y <- f0(x,a,b)

par(mfrow=c(1,2),mar=c(2.5,2.5,1,0.25))
plot(x,y,type='l',xlim=c(90,110), ylim = c(0,1))
mtext('For f0: a=98, b=102', side = 3, line = 0)

a <- 100
x <- seq(a,b,0.1)
y <- f0(x,a,b)

plot(x,y,type='l',xlim=c(90,110), ylim = c(0,1))
mtext('change a=100 (keep b=102)', side = 3, line = 0)
```

---

*Source: [Class.7 on byuimath.com](https://byuimath.com/clarkc/all/119/index.php?n=Class.7)*
