---
title: "Class 11"
---

# During Class - Day 11
## Brain Gains
1. Suppose $f(x;a,b) = a e^{b x}$. If $f(0)=7$, then what must $a$ equal?

1. Suppose $f(x;a,b) = a+b e^{x}$. If $f(0)=7$, then what must $a$ equal?
1. Use uniroot to solve for $x$ in $7 = 5+3 e^{2 x}$. Check your solution by finding the exact solution, if possible.

1. Use uniroot to solve for $x$ in $(-13 + 2x)e^{-0.05x} = 0$. Check your solution by finding the exact solution, if possible.
    - Use uniroot to solve for $x$ in $(-13 + 2x)e^{-0.05x} = 5$. Check your solution by finding the exact solution, if possible.

## Discussion - Task 3
Visually Fitting Models

### Example Project
We need to visually fit each of the 3 models to the data by selecting parameters so the model looks as much like the data as possible. We may not succeed, but we can try to get as close as possible. 
Use the code below to construct a histogram of percent lumen intensity **all the bulbs**. 

```r
rm(list=ls())
library(data4led)
dist <- led_time(2100)
hist(dist$percent_intensity,probability = TRUE)
```

By identifying the characteristics we see in the data we know what behavior we would like the function curve to have.
- What characteristics do you notice about the density histogram of our data?
    - What is the smallest value?
    - What is the largest value?
    - What is the location of the peak?
    - What is the width of the peak?

- What did you notice about the general model $f_0$ and its parameters?<br>
$f_0(x;a,b) = \frac{1}{b-a}$ with $ -\infty < a < x < b < \infty $
    - What is the domain of $f_0$?
[Desmos file for function $f_0$ (Example Project)](https://www.desmos.com/calculator/is6afqy4yd){target="_blank"}
    - What does $a$ do?
    - What does $b$ do?
Let's summarize our observations with a few plots.For example, the following code creates side-by-side representative curves for the parameter $a$ from 92 to 98 while keeping $b$ at 104 in function $f_0$. We can adapt the code to explore different parameters. 

```r
f0 <- function(x,a=0,b=1){
  # Make sure a < b when using this function.
  ifelse((a < x) & (x < b), 1/(b-a) + 0*x[(a < x) & (x < b)],NaN)
}

#Change these values as needed to compare plots. 
a1 <- 92
a2 <- 98

b1 <- 104
b2 <- 104

x <- seq(min(a1,a2),max(b1,b2),0.1)
y1 <- f0(x,a1,b1)
y2 <- f0(x,a2,b2)

xlimits = c(min(a1,a2)-2,max(b1,b2)+2)
ylimits = c(0,1)

par(mfrow=c(1,2),mar=c(2.5,2.5,2,0.25),oma=c(0,0,1,0))
plot(x,y1,type='l',xlim=xlimits,ylim=ylimits)
mtext(paste('a =',a1," and b=",b1), side = 3, line = 0)
plot(x,y2,type='l',xlim=xlimits,ylim=ylimits)
mtext(paste('a =',a2," and b=",b2), side = 3, line = 0)
mtext('Plot of f0',side=3,line=0,outer=TRUE)
```

For the model $f_0$, introduced in Task 2, we can plot $f_0(L; a, b)$ fitted to the data in the same plot as the histogram using this code.

```r
f0 <- function(x,a=0,b=1){
  # Make sure a < b when using this function.
  1/(b-a) + 0*x
}

a <- 99.5
b <- 103.5

x <- seq(a,b,0.01)
y <- f0(x,a=a,b=b)

par(mfrow=c(1,1),mar=c(2,2,3,0.25),oma=rep(0.5,4))
hist(dist$percent_intensity,
     probability = TRUE,
     xlim=c(98,105),
     ylim=c(0,0.8),
     main="Histogram of Lightbulb Intensities \n with fitted f0 function")
lines(x,y,col=2)
```

### Project 1
We need to visually fit each of the 6 models to the data by selecting parameters so the model looks as much like the data as possible. 
 
The code below uses the random seed 123 to construct a scatter plot of percent lumen intensity for **a single bulb** as *a function of time in hours*.
During class, please use the same seed (123) so that we can help one another fit values. When you work on your own project, you'll need to adjust the seed.  

```r
library(data4led)
bulb <- led_bulb(1,seed = 123)
    
t <- bulb$hours
y1 <- bulb$percent_intensity

par(mfrow=c(1,1),mar=c(2,2,3,0.25),oma=rep(0.5,4))
plot(t,y1,xlab="Hour", ylab="Intensity(%) ", pch=16)
```

By identifying the characteristics we see in the data we know what behavior we would like the function curve to have.
- What characteristics do you notice about the scatter plot of our data?
    - What is the range of values for the intensities? 
    - What is the range of times?
    - What behaviors do you see in the data?

The prep for today had you try visually fitting parameters to function $f_5$.  Let's head up to the prep, rerun the relevant code, and discuss what you tried.  Then we'll spend the rest of the hour, in groups, trying to obtain a reasonably good visual fit for the other models, using the seed 123. This is precisely what Project 1 Task 3 has you do. 
- If using Desmos to help you make choices, realize you can change the range and step size for each slider. 

## Group Meeting 

Start by giving each person a moment to share what they chose to prepare for class. Help each other address any questions.  When each person has had a chance to share, move on the other activities.

### Activity - Project 1 Task 3 Collaboration
1. As a group, run the code below and then critique the visual fit for $f_1$ obtained by letting $a_0 = 101$ and $a_1=0.00025$. 

```r
f1 <- function(x,a0=0,a1=0){ a0 + a1*x }

x <- seq(-10,80001,2)
yM <- f1(x,a0=101,a1=0.00025)

par(mfrow=c(1,2),mar=c(2,2,3,0.25),oma=rep(0.5,4))
plot(t,y1,xlab="Hour ", ylab="Intensity(%) ", pch=16,main='f1')
lines(x,yM,col=2)
plot(t,y1,xlab="Hour ", ylab="Intensity(%) ", pch=16, xlim = c(-10,80000),ylim = c(-10,120))
lines(x,yM,col=2)
```

2. Tell the story given by the model provided above? What story does the model give at time 0? What story does the model tell as time increases?  

3. What story does the data tell at time 0? Does the story told by the model match the information from the data at time 0?  

4. Update the parameters above to obtain a visual fit that satisfies $f_1(0)=100$.  Then use the [shiny app](https://shiny.byui.edu/connect/#/apps/0d605bec-7069-4d67-8129-8716269e8816/access) to check your work.

5. Using the seed 123, adapt the code above to provide a good fit for model $f_4$. By using the same seed, you can compare your plots and work together to find reasonable values for each parameter. When you complete the project, you'll need to change the seed to yours, and then make some minor modifications to your parameters. 

6. What story is told by the visual fit you found for $f_4$? 

7. With any time remaining, tackle the other models together, obtaining reasonable fits using the seed 123.

---

*Source: [Class.11 on byuimath.com](https://byuimath.com/clarkc/all/119/index.php?n=Class.11)*
