---
title: "Unit 2 Project"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!
set.seed(NULL) #The seed will be different for each student when the student replaces "NULL" with their seed. (each student will have their own data)
devtools::install_github('byuidatascience/data4led')
library(data4led)

ids <- unique(led_study$id)
bulb <- sample(ids,1)
idx <- which(led_study == bulb)
bulb.data = 100*led_study$percent_intensity[idx]
```
<!-- #Color Format -->
<!-- colText = function(x,color){ -->
<!--   outputFormat = knitr::opts_knit$get("rmarkdown.pandoc.to") -->
<!--   if(outputFormat == 'latex') -->
<!--     paste("\\textcolor{",color,"}{",x,"}",sep="") -->
<!--   else if(outputFormat == 'html') -->
<!--     paste("<font color='",color,"'>",x,"</font>",sep="") -->
<!--   else -->
<!--     x -->
<!-- } -->


<!-- ## BackGround -->


<!-- #Week 1 -->
##Statistic -- A number that summarizes information from data.



```{r}

```


<!-- #Week 2 -->
##Optimize Likelihood Function

```{r, error=TRUE}

```

<!-- #Week 3 -->
##Use the Model
  

```{r}

```

<!-- #Week 4 -->
##Assume a Different Functional Form for the Model


```{r}

```

## Conclusions


## Reflection
