---
title: "Comparing Least Squares and Maximum Likelihood"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Let $f(x) = \beta_0 + \beta_1 x + \beta x^2 + \beta_3 x^3$. This is our "relationship model". It describes a relationship between the independent variable $x$ and the dependent variable $y$.

Suppose we have 50 data points, $(x_i,y_i)$ where $i = 1, 2, ... , 50$. We can calculate the error (or residual), the distance between the observed value, $y_i$, and value predicted by the model, $f(x_i)$, for each of the 50 points. We have $\text{error}_i = y_i - f(x_i) = y_i - (\beta_0 + \beta_1 x_i + \beta_2 x_i^2 + \beta_3 x_i^3)$.

If we assume these errors are normally distributed. Then we know each of the errors will follow the normal probability model, a "measurement model", $p(\text{error}_i) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\text{error}_i^2}$. If we assume these errors are independent, then the combine probability model for the errors will be $p(\text{errors}) = \prod_{i=1}^{50}\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\text{error}_i^2}$. Remember the errors are a function of the data ($x$ and $y$) and the parameters of $f$ ($\beta_0$, $\beta_1$, $\beta_2$, and $\beta_3$). If $\beta_0$, $\beta_1$, $\beta_2$, and $\beta_3$ are fixed (the parameters are know, $f$ is a specific rather than general model), then $p(\text{errors})$ is a probability density function that depends on the 50 $x$'s and 50 $y$'s. If $x$ and $y$ are fixed (the data is known), then $p(\text{errors})$ is a likelihood function that depends on the parameters of $f$, $\beta_0$, $\beta_1$, $\beta_2$, and $\beta_3$.

Once we have determined the function we want to maximize (or minimum if desired), we can optimize. To optimize we take the first derivatives, set the first derivatives equal to zero and solve to find the critical points, and then verify that we have a maximum (or minimum if desired). In this case we want to maximize the likelihood function, $L(\beta_0, \beta_1, \beta_2, \beta_3; \mathbf{x},\mathbf{y}) = \prod_{i=1}^{50}\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)^2}$. Taking a derivative of a sum is much simpler than taking the derivative of a product and it turns out that the natural logarithm of a function and the function have maximums in the same location, so we will maximize the natural log of the likelihood instead of the likelihood. So we will maximize, $\ell(\beta_0, \beta_1, \beta_2, \beta_3; \mathbf{x},\mathbf{y}) = \ln(L(\beta_0, \beta_1, \beta_2, \beta_3; \mathbf{x},\mathbf{y})) = 50\ln(\frac{1}{\sqrt{2\pi}}) -\frac{1}{2}\sum_{i=1}^{50}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)^2$.

First we need to take the first derivatives of $\ell$. We find the following.

* $\frac{d\ell}{d\beta_0} = \sum_{i=1}^{50}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)$

* $\frac{d\ell}{d\beta_1} = \sum_{i=1}^{50}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)x_i$

* $\frac{d\ell}{d\beta_2} = \sum_{i=1}^{50}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)x_i^2$

* $\frac{d\ell}{d\beta_3} = \sum_{i=1}^{50}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)x_i^3$

Next we need set the derivatives equal to zero and solve. We need to solve the following system of equations.
$\left\{
\begin{array}{ll}
\sum y_i - 50\beta_0 - \beta_1 \sum x_i - \beta_2 \sum x_i^2 - \beta_3 \sum x_i^3 &= 0 \\ 
\sum x_iy_i - \beta_0 \sum x_i - \beta_1 \sum x_i^2 - \beta_2 \sum x_i^3 - \beta_3 \sum x_i^4 &= 0 \\ 
\sum x_i^2y_i - \beta_0 \sum x_i^2 - \beta_1 \sum x_i^3 - \beta_2 \sum x_i^4 - \beta_3 \sum x_i^5 &= 0 \\ 
\sum x_i^3y_i - \beta_0 \sum x_i^3 - \beta_1 \sum x_i^4 - \beta_2 \sum x_i^5 - \beta_3 \sum x_i^6 &= 0.
\end{array} 
\right.$

Remember all the sums ($\sum y_i$, $\sum x_iy_i$, ... $\sum x_i^3y_i$, $\sum x_i$, $\sum x_i^2$, ... $\sum x_i^6$) are constants and can be calculated very easily in R since the data is known. And notice the system above is a linear system in the variables $\beta_0$, $\beta_1$, $\beta_2$, and $\beta_3$. Note we can write this system in matrix form.

$\begin{bmatrix} \sum y_i & -50 & -\sum x_i & -\sum x_i^2 & -\sum x_i^3\\ \sum x_iy_i & -\sum x_i & -\sum x_i^2 & -\sum x_i^3 & -\sum x_i^4 \\ \sum x_i^2y_i & -\sum x_i^2 & -\sum x_i^3 & -\sum x_i^4 & -\sum x_i^5 \\ \sum x_i^3y_i & -\sum x_i^3 & -\sum x_i^4 & -\sum x_i^5 & -\sum x_i^6 \end{bmatrix} \begin{bmatrix} 1 \\ \beta_0 \\ \beta_1 \\ \beta_2 \\ \beta_3 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}$

When you solve this system you will have the values of $\beta_0$, $\beta_1$, $\beta_2$, and $\beta_3$ (a critical point). You can check that this critical point is the location of a maximum using the second derivative test. In Math 119, we only use the second derivative test in one dimension and in two dimensions but the second derivative test generalizes to higher dimensions, [see this article](http://faculty.csuci.edu/brian.sittinger/2nd_DerivTest.pdf).

Once you have the values for the parameters $\beta_0$, $\beta_1$, $\beta_2$, and $\beta_3$ you can define your function $f(x) = \beta_0 + \beta_1 x + \beta x^2 + \beta_3 x^3$ in R. Then plot your data and the fitted function in the same plot. Once you have your values for $\beta_0$, $\beta_1$, $\beta_2$ and $\beta_3$ (you have fit your function to your data), if you have trouble plotting your fitted function with your data, send me your data and your values for $\beta_0$, $\beta_1$, $\beta_2$ and $\beta_3$ and I would be happy to send you code that will plot both on the same graph.

A final note, the assumptions of the least squares problem are the errors (the residual) are normal and independent. These are the same assumptions we made when writing the likelihood function above. If we wanted to make different assumptions we could find the new likelihood function (dependent upon the assumptions) and redo the calculations above. Depending on how you change the assumptions the problem gets much harder.

It turns out with the assumptions that the errors are normal and independent, the least squares problem and the maximize the loglikelihood problem for fitting a model are very similar. Both are optimization problems so use the basic optimization method we (1) need to write down the function we want to optimize -- we call this the objective function, (2) take the first derivatives, (3) set the first derivatives equal to zero and solve the system to find the critical points, and (4) verify that we have a maximum or minimum using the second derivative test. In the case of the loglikelihood method the objective function is $\ell(\beta_0, \beta_1, \beta_2, \beta_3) = 50\ln(\frac{1}{\sqrt{2\pi}}) -\frac{1}{2}\sum_{i=1}^{50}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)^2$ and we would like to maximize the objective function. In the case of the least squares method the objective function is the sum of the squared errors, $h(\beta_0, \beta_1, \beta_2, \beta_3) = \sum_{i=1}^{50}(y_i - \beta_0 - \beta_1 x_i - \beta_2 x_i^2 - \beta_3 x_i^3)^2$, and we would like to minimize the objective function. Notice $\ell$ is just a transformation of $h$ (reflected vertically and shifted down). This means that the $h$ will have a minimum at the same location (the same values for the parameters $\beta_0$, $\beta_1$, $\beta_2$, $\beta_3$) that $\ell$ will have a maximum.