#!/usr/bin/env python3
"""Generate site/_today.qmd, site/schedule_full.json, and schedule_visual.md from schedule_config.yml.

Run manually:  uv run python tools/generate_schedule.py
Run in CI:     python tools/generate_schedule.py  (uv venv activated)
"""

import json
import sys
from datetime import date, timedelta
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent
CONFIG_PATH = REPO_ROOT / "schedule_config.yml"
SITE_DIR = REPO_ROOT / "site"
TODAY_QMD = SITE_DIR / "_today.qmd"
SCHEDULE_JSON = SITE_DIR / "schedule_full.json"
VISUAL_MD = REPO_ROOT / "schedule_visual.md"

DAY_ABBR = {0: "Mon", 1: "Tue", 3: "Thu", 4: "Fri"}

WEEKDAY_MAP = {"Mon": 0, "Tue": 1, "Wed": 2, "Thu": 3, "Fri": 4, "Sat": 5, "Sun": 6}

SESSION_LABELS = {
    "review":  "Review Day",
    "project": "Project Work Day",
    "testing": "Testing Day",
    "holiday": "(No Class)",
}


def parse_config():
    return yaml.safe_load(CONFIG_PATH.read_text())


def build_calendar(config: dict) -> list[dict]:
    """Map each session to a date, returning a list of {date, session, label, link}."""
    start = date.fromisoformat(config["semester"]["start"])
    end   = date.fromisoformat(config["semester"]["end"])
    class_days = {WEEKDAY_MAP[d] for d in config["semester"]["class_days"]}
    holidays = {date.fromisoformat(h["date"]): h["name"] for h in config.get("holidays", [])}
    sessions = config["sessions"]

    calendar = []
    session_idx = 0
    current = start

    while current <= end and session_idx < len(sessions):
        if current.weekday() not in class_days:
            current += timedelta(days=1)
            continue

        if current in holidays:
            calendar.append({
                "date": current.isoformat(),
                "session": "holiday",
                "label": holidays[current],
                "link": None,
                "is_holiday": True,
            })
            current += timedelta(days=1)
            continue

        session = sessions[session_idx]
        session_idx += 1

        entry = {"date": current.isoformat(), "session": session, "is_holiday": False}

        if session.startswith("class-"):
            num = session.split("-")[1]
            entry["label"] = f"Class {num}"
            entry["link"] = f"class/class-{num}.html"
        elif session.startswith("flex-"):
            num = session.split("-")[1]
            entry["label"] = f"Flex Day {num}"
            entry["link"] = f"flex/flex-{num}.html"
        else:
            entry["label"] = SESSION_LABELS.get(session, session.title())
            entry["link"] = None

        calendar.append(entry)
        current += timedelta(days=1)

    return calendar


def find_today_entry(calendar: list[dict], today: date) -> dict | None:
    today_str = today.isoformat()
    for entry in calendar:
        if entry["date"] == today_str:
            return entry
    return None


def find_next_class(calendar: list[dict], today: date) -> dict | None:
    today_str = today.isoformat()
    for entry in calendar:
        if entry["date"] > today_str and not entry.get("is_holiday") and entry["session"] not in ("review", "testing", "project"):
            return entry
    return None


def write_today_qmd(calendar: list[dict], today: date):
    today_entry = find_today_entry(calendar, today)
    next_entry = find_next_class(calendar, today)

    lines = ["---\n# Auto-generated by tools/generate_schedule.py — do not edit manually\n---\n"]

    if today_entry and not today_entry.get("is_holiday"):
        label = today_entry["label"]
        link = today_entry["link"]
        if link:
            lines.append(f"## Today: [{label}]({link})\n")
        else:
            lines.append(f"## Today: {label}\n")
    elif today_entry and today_entry.get("is_holiday"):
        lines.append(f"## Today: No Class — {today_entry['label']}\n")
    else:
        lines.append("## No class today.\n")

    if next_entry:
        label = next_entry["label"]
        link = next_entry["link"]
        date_obj = date.fromisoformat(next_entry["date"])
        date_fmt = date_obj.strftime("%A, %b %-d")
        if link:
            lines.append(f"**Next class:** [{label}]({link}) — {date_fmt}\n")
        else:
            lines.append(f"**Next class:** {label} — {date_fmt}\n")

    SITE_DIR.mkdir(exist_ok=True)
    TODAY_QMD.write_text("\n".join(lines))
    print(f"Wrote {TODAY_QMD.relative_to(REPO_ROOT)}")


def write_schedule_json(calendar: list[dict]):
    SCHEDULE_JSON.write_text(json.dumps(calendar, indent=2))
    print(f"Wrote {SCHEDULE_JSON.relative_to(REPO_ROOT)}")


def _load_class_topics() -> dict[int, str]:
    """Return {class_num: first ### heading under '# During Class'} per class .qmd.

    The first `###` overall is always a Prep step like "(1) Foo" — not useful as
    a schedule topic. Skip past `# During Class` and take the first `###` from
    there (the in-class activity heading).
    """
    topics = {}
    class_dir = SITE_DIR / "class"
    if not class_dir.exists():
        return topics
    for qmd in class_dir.glob("class-*.qmd"):
        try:
            num = int(qmd.stem.split("-")[1])
        except (IndexError, ValueError):
            continue
        in_class_section = False
        for line in qmd.read_text(errors="replace").splitlines():
            if line.startswith("# During Class"):
                in_class_section = True
                continue
            if in_class_section and line.startswith("### "):
                topics[num] = line[4:].strip()
                break
    return topics


def write_schedule_qmd(calendar: list[dict], config: dict):
    """Overwrite site/schedule.qmd with a week × MTRF markdown table."""
    out_path = SITE_DIR / "schedule.qmd"
    semester = config["semester"]
    start = date.fromisoformat(semester["start"])
    end   = date.fromisoformat(semester["end"])

    topics = _load_class_topics()
    by_date = {e["date"]: e for e in calendar}

    class_weekdays = [WEEKDAY_MAP[d] for d in semester["class_days"]]
    col_names = [d for d in ["Mon", "Tue", "Thu", "Fri"] if WEEKDAY_MAP[d] in class_weekdays]
    col_wdays = [WEEKDAY_MAP[n] for n in col_names]

    header = "| Week | " + " | ".join(col_names) + " |"
    sep    = "| --- | " + " | ".join("---" for _ in col_names) + " |"

    rows = []
    week_start = start - timedelta(days=start.weekday())
    week_num = 0
    current_week = week_start
    while current_week <= end:
        days_in_sem = [
            current_week + timedelta(days=wd - current_week.weekday())
            for wd in col_wdays
        ]
        if not any(start <= d <= end for d in days_in_sem):
            current_week += timedelta(weeks=1)
            continue

        week_num += 1
        cells = []
        for wd in col_wdays:
            d = current_week + timedelta(days=wd - current_week.weekday())
            if d < start or d > end:
                cells.append("—")
                continue
            entry = by_date.get(d.isoformat())
            if entry is None:
                cells.append("—")
            elif entry["is_holiday"]:
                cells.append(f"🚫 {entry['label']}")
            elif entry["session"].startswith("class-"):
                num = int(entry["session"].split("-")[1])
                topic = topics.get(num, "")
                date_str = d.strftime("%-m/%-d")
                cell = f"{date_str} [{f'Day {num}'}]({entry['link']}):"
                if topic:
                    cell += f"<br>{topic}"
                cells.append(cell)
            elif entry["session"].startswith("flex-"):
                num = entry["session"].split("-")[1]
                date_str = d.strftime("%-m/%-d")
                cells.append(f"{date_str} [Flex {num}]({entry['link']})")
            else:
                label = SESSION_LABELS.get(entry["session"], entry["session"].title())
                cells.append(f"{d.strftime('%-m/%-d')} {label}")

        rows.append("| **W" + str(week_num) + "** | " + " | ".join(cells) + " |")
        current_week += timedelta(weeks=1)

    content = f"""---
title: "Schedule"
---

::: {{.schedule-grid}}
{header}
{sep}
""" + "\n".join(rows) + "\n:::\n"

    out_path.write_text(content)
    print(f"Wrote {out_path.relative_to(REPO_ROOT)}")


def write_schedule_visual(calendar: list[dict], config: dict):
    """Write schedule_visual.md — a week × MTRF grid for faculty review."""
    start = date.fromisoformat(config["semester"]["start"])
    end   = date.fromisoformat(config["semester"]["end"])
    semester = config["semester"]

    # Index calendar by date string for fast lookup
    by_date = {e["date"]: e for e in calendar}

    # Walk week by week (Mon–Sun) across the semester
    # Find the Monday of the start week
    week_start = start - timedelta(days=start.weekday())  # Mon of first week

    class_weekdays = [WEEKDAY_MAP[d] for d in semester["class_days"]]
    col_names = [d for d in ["Mon", "Tue", "Thu", "Fri"] if WEEKDAY_MAP[d] in class_weekdays]
    col_wdays = [WEEKDAY_MAP[n] for n in col_names]

    lines = [
        f"# Math 119 — SP26 Schedule Visual",
        f"",
        f"Generated from `schedule_config.yml`. Edit that file to adjust pacing, then run:",
        f"`uv run python tools/generate_schedule.py`",
        f"",
        f"**Semester:** {start.strftime('%b %-d')} – {end.strftime('%b %-d, %Y')}  ",
        f"**Class days:** {', '.join(semester['class_days'])}",
        f"",
    ]

    # Table header
    col_header = " | ".join(col_names)
    col_sep = " | ".join(["---"] * len(col_names))
    lines.append(f"| Week | {col_header} |")
    lines.append(f"|------|{col_sep}|")

    week_num = 0
    current_week = week_start
    while current_week <= end:
        week_end = current_week + timedelta(days=6)
        # Only count weeks that have at least one class day in the semester
        days_in_semester = [
            current_week + timedelta(days=wd - current_week.weekday())
            for wd in col_wdays
        ]
        if not any(start <= d <= end for d in days_in_semester):
            current_week += timedelta(weeks=1)
            continue

        week_num += 1
        cells = []
        for wd in col_wdays:
            d = current_week + timedelta(days=wd - current_week.weekday())
            if d < start or d > end:
                cells.append("—")
                continue
            entry = by_date.get(d.isoformat())
            if entry is None:
                cells.append("—")
            elif entry["is_holiday"]:
                cells.append(f"🚫 {entry['label']}")
            elif entry["session"].startswith("class-"):
                num = entry["session"].split("-")[1]
                cells.append(f"Day {num} ({d.strftime('%-m/%-d')})")
            elif entry["session"].startswith("flex-"):
                num = entry["session"].split("-")[1]
                cells.append(f"Flex {num} ({d.strftime('%-m/%-d')})")
            else:
                label = SESSION_LABELS.get(entry["session"], entry["session"].title())
                cells.append(f"{label} ({d.strftime('%-m/%-d')})")

        lines.append(f"| W{week_num:<2} | {' | '.join(cells)} |")
        current_week += timedelta(weeks=1)

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*To shift pacing: edit `sessions:` in `schedule_config.yml`, then re-run the generator.*")

    VISUAL_MD.write_text("\n".join(lines))
    print(f"Wrote {VISUAL_MD.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    if not CONFIG_PATH.exists():
        sys.exit(f"ERROR: {CONFIG_PATH} not found.")

    config = parse_config()
    calendar = build_calendar(config)

    # Allow overriding today for testing: python generate_schedule.py 2026-05-19
    today = date.fromisoformat(sys.argv[1]) if len(sys.argv) > 1 else date.today()

    write_today_qmd(calendar, today)
    write_schedule_json(calendar)
    write_schedule_qmd(calendar, config)
    write_schedule_visual(calendar, config)

    print(f"Done. Calendar has {len(calendar)} entries ({today.isoformat()} = today).")
