---
title: "Example Project Task 2"
author: "Math 119 Class"
date: "1/15/2021"
output: 
  html_document:
    code_folding: hide
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

$f_0(L)$
$b=107$
first plot $a=91$
second plot $a=98$
```{r}
f0 <- function(L,a=0,b=1){
# Make sure a < L < b when using this function. Also make sure a < b.
rep(1/(b-a),length(L))
}

b <- 107
par(mfrow=c(1,2),mar=c(2.5,2.5,1,0.25),oma=c(0.1,0.1,1,0.1))
a1 <- 91
L1 <- seq(a1,b,0.1)
plot(L1,f0(L1,a1,b),type='l',xlim=c(90,110),ylim=c(0,0.14))
a2 <- 98
L2 <- seq(a2,b,0.1)
plot(L2,f0(L2,a2,b),type='l',xlim=c(90,110),ylim=c(0,0.14))
mtext('Changing a in f0', side = 3, line = 0, outer = TRUE)
```

$f_1(L)$
$a=1$
first plot $h=90$
second plot $h=100$
```{r}
f1 <- function(L,h=0,a=1){
# This function can be evaluated at any value of L. Make sure h > 0 and a > 0.
1/sqrt(2*pi*a)*exp(-(L-h)^2/(2*a))
}

a <- 1
L <- seq(80,120,0.1)
par(mfrow=c(1,2),mar=c(2.5,2.5,1,0.25),oma=c(0.1,0.1,1,0.1))
h1 <- 90
plot(L,f1(L,h1,a),type='l',xlim=c(80,120))
h2 <- 100
plot(L,f1(L,h2,a),type='l',xlim=c(80,120))
mtext('Changing h in f1', side = 3, line = 0, outer = TRUE)
```

$f_1(L)$
$h =90$
first plot $a=1$
second plot $a=4$
```{r}
h <- 90
L <- seq(80,120,0.1)
par(mfrow=c(1,2),mar=c(2.5,2.5,1,0.25),oma=c(0.1,0.1,1,0.1))
a1 <- 1
plot(L,f1(L,h,a1),type='l',xlim=c(80,120),ylim=c(0,0.4))
a2 <- 4
plot(L,f1(L,h,a2),type='l',xlim=c(80,120),ylim=c(0,0.4))
mtext('Changing a in f1', side = 3, line = 0, outer = TRUE)
```

$f_2(L)$
$a=?$ and $b=?$
first plot $h=?$
second plot $h=?$
```{r}
f2 <- function(L,h=0,a=1,b=5){
# Make sure L is greater than or equal to h when using this function. Also make sure a > 0 and b > 0.
b^a/gamma(a)*(L-h)^(a-1)*exp(-b*(L-h))
}

# a <- [your selected value]
# b <- [your selected value]
# 
# par(mfrow=c(1,2),mar=c(2.5,2.5,1,0.25),oma=c(0.1,0.1,1,0.1))
# h1 <- [your selected value]
# L1 <- seq(h1,120,0.1)
# plot(L1,f2(L1,h1,a,b),type='l',xlim=c(80,120))
# h2 <- [your selected value]
# L2 <- seq(h2,120,0.1)
# plot(L2,f2(L2,h2,a,b),type='l',xlim=c(80,120))
# mtext('Changing h in f2', side = 3, line = 0, outer = TRUE)
```

$f_2(L)$
$h=?$ and $b=?$
first plot $a=?$
second plot $a=?$
```{r}
# h <- [your selected value]
# b <- [your selected value]
# L <- seq(h,120,0.1)
# 
# par(mfrow=c(1,2),mar=c(2.5,2.5,1,0.25),oma=c(0.1,0.1,1,0.1))
# a1 <- [your selected value]
# plot(L,f2(L,h,a1,b),type='l',xlim=c(80,120))
# a2 <- [your selected value]
# plot(L,f2(L,h,a2,b),type='l',xlim=c(80,120))
# mtext('Changing a in f2', side = 3, line = 0, outer = TRUE)
```

$f_2(L)$
$h=?$ and $a=?$
first plot $b=?$
second plot $b =?$
```{r}
# h <- [your selected value]
# a <- [your selected value]
# L <- seq(h,120,0.1)
# 
# par(mfrow=c(1,2),mar=c(2.5,2.5,1,0.25),oma=c(0.1,0.1,1,0.1))
# b1 <- [your selected value]
# plot(L,f2(L,h,a,b1),type='l',xlim=c(80,120))
# b2 <- [your selected value]
# plot(L,f2(L,h,a,b2),type='l',xlim=c(80,120))
# mtext('Changing b in f2', side = 3, line = 0, outer = TRUE)
```